package com.liurq.server.dao;

import com.liurq.server.model.DoctorVisit;
import com.liurq.server.model.DoctorVisitExample;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface DoctorVisitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_visit
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int countByExample(DoctorVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_visit
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int deleteByExample(DoctorVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_visit
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_visit
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int insert(DoctorVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_visit
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int insertSelective(DoctorVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_visit
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    List<DoctorVisit> selectByExample(DoctorVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_visit
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    DoctorVisit selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_visit
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByExampleSelective(@Param("record") DoctorVisit record, @Param("example") DoctorVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_visit
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByExample(@Param("record") DoctorVisit record, @Param("example") DoctorVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_visit
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByPrimaryKeySelective(DoctorVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_visit
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByPrimaryKey(DoctorVisit record);

    /**
     * 查询医生指定日期的出诊
     * @param param
     * @return
     */
    DoctorVisit selectVisitByStartTime(Map<String,Object> param);

    /**
     * 查询挂号详情
     * @param doctorId
     * @return
     */
    List<DoctorVisit> selectVisitList(String doctorId);

    /**
     * 查询已经挂号的号码
     * @param visitId
     * @return
     */
    List<Integer> selectVisitNum(String visitId);

    /**
     * 查询医生当前挂号
     * @param param
     * @return
     */
    DoctorVisit selectNowVisit(Map<String,Object> param);

    /**
     * 查询医生的出诊安排
     * @param doctorId
     * @return
     */
    List<DoctorVisit> selectDoctorVisitList(String doctorId, Date startDate);
}