package com.liurq.server.dao;

import com.liurq.server.model.HospitalType;
import com.liurq.server.model.HospitalTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HospitalTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_type
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    int countByExample(HospitalTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_type
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    int deleteByExample(HospitalTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_type
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_type
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    int insert(HospitalType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_type
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    int insertSelective(HospitalType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_type
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    List<HospitalType> selectByExample(HospitalTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_type
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    HospitalType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_type
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    int updateByExampleSelective(@Param("record") HospitalType record, @Param("example") HospitalTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_type
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    int updateByExample(@Param("record") HospitalType record, @Param("example") HospitalTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_type
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    int updateByPrimaryKeySelective(HospitalType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_type
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    int updateByPrimaryKey(HospitalType record);
}