package com.liurq.server.dao;

import com.liurq.server.model.Department;
import com.liurq.server.model.HospitalDepartment;
import com.liurq.server.model.HospitalDepartmentExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface HospitalDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_department
     *
     * @mbggenerated Thu Apr 01 15:07:50 CST 2021
     */
    int countByExample(HospitalDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_department
     *
     * @mbggenerated Thu Apr 01 15:07:50 CST 2021
     */
    int deleteByExample(HospitalDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_department
     *
     * @mbggenerated Thu Apr 01 15:07:50 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_department
     *
     * @mbggenerated Thu Apr 01 15:07:50 CST 2021
     */
    int insert(HospitalDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_department
     *
     * @mbggenerated Thu Apr 01 15:07:50 CST 2021
     */
    int insertSelective(HospitalDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_department
     *
     * @mbggenerated Thu Apr 01 15:07:50 CST 2021
     */
    List<HospitalDepartment> selectByExample(HospitalDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_department
     *
     * @mbggenerated Thu Apr 01 15:07:50 CST 2021
     */
    HospitalDepartment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_department
     *
     * @mbggenerated Thu Apr 01 15:07:50 CST 2021
     */
    int updateByExampleSelective(@Param("record") HospitalDepartment record, @Param("example") HospitalDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_department
     *
     * @mbggenerated Thu Apr 01 15:07:50 CST 2021
     */
    int updateByExample(@Param("record") HospitalDepartment record, @Param("example") HospitalDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_department
     *
     * @mbggenerated Thu Apr 01 15:07:50 CST 2021
     */
    int updateByPrimaryKeySelective(HospitalDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_department
     *
     * @mbggenerated Thu Apr 01 15:07:50 CST 2021
     */
    int updateByPrimaryKey(HospitalDepartment record);

    /**
     * 删除医院下所有的科室信息
     * @param param
     * @return
     */
    int deleteAllHospitalDepartment(Map<String,Object> param);

    /**
     *
     * @param hospitalId
     * @param departmentId
     * @param status
     * @return
     */
    int updateMajorDepartment(String hospitalId,String departmentId,String isMajor);

    /**
     *
     * @param hospitalId
     * @param departmentId
     * @return
     */
    int updateStatus(String hospitalId,String departmentId,String status);

}