package com.liurq.server.dao;

import com.liurq.server.model.HospitalGuide;
import com.liurq.server.model.HospitalGuideExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HospitalGuideMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_guide
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    int countByExample(HospitalGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_guide
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    int deleteByExample(HospitalGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_guide
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_guide
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    int insert(HospitalGuide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_guide
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    int insertSelective(HospitalGuide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_guide
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    List<HospitalGuide> selectByExampleWithBLOBs(HospitalGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_guide
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    List<HospitalGuide> selectByExample(HospitalGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_guide
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    HospitalGuide selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_guide
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    int updateByExampleSelective(@Param("record") HospitalGuide record, @Param("example") HospitalGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_guide
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") HospitalGuide record, @Param("example") HospitalGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_guide
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    int updateByExample(@Param("record") HospitalGuide record, @Param("example") HospitalGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_guide
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    int updateByPrimaryKeySelective(HospitalGuide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_guide
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(HospitalGuide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_hospital_guide
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    int updateByPrimaryKey(HospitalGuide record);
}