package com.liurq.server.dao;

import com.liurq.server.model.Hospital;
import com.liurq.server.model.HospitalExample;
import java.util.List;

import com.liurq.server.restful.req.hospital.SelectHospitalByDepartmentReq;
import com.liurq.server.restful.rsp.hospital.SelectHospitalRsp;
import org.apache.ibatis.annotations.Param;

public interface HospitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sun Mar 21 12:20:21 CST 2021
     */
    int countByExample(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sun Mar 21 12:20:21 CST 2021
     */
    int deleteByExample(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sun Mar 21 12:20:21 CST 2021
     */
    int deleteByPrimaryKey(String hospitalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sun Mar 21 12:20:21 CST 2021
     */
    int insert(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sun Mar 21 12:20:21 CST 2021
     */
    int insertSelective(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sun Mar 21 12:20:21 CST 2021
     */
    List<Hospital> selectByExampleWithBLOBs(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sun Mar 21 12:20:21 CST 2021
     */
    List<Hospital> selectByExample(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sun Mar 21 12:20:21 CST 2021
     */
    Hospital selectByPrimaryKey(String hospitalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sun Mar 21 12:20:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") Hospital record, @Param("example") HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sun Mar 21 12:20:21 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") Hospital record, @Param("example") HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sun Mar 21 12:20:21 CST 2021
     */
    int updateByExample(@Param("record") Hospital record, @Param("example") HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sun Mar 21 12:20:21 CST 2021
     */
    int updateByPrimaryKeySelective(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sun Mar 21 12:20:21 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sun Mar 21 12:20:21 CST 2021
     */
    int updateByPrimaryKey(Hospital record);

    /**
     * 根据部门查询医院信息
     * @param req
     * @return
     */
    List<SelectHospitalRsp> selectHospitalByDepartment(SelectHospitalByDepartmentReq req);

    /**
     * 查询医院id
     * @param doctorId
     * @return
     */
    Hospital selectHospitalIdByDoctorId(String doctorId);
}