package com.liurq.server.dao;

import com.liurq.server.model.Knowledge;
import com.liurq.server.model.KnowledgeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KnowledgeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_knowledge
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int countByExample(KnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_knowledge
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int deleteByExample(KnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_knowledge
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int deleteByPrimaryKey(String knowledgeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_knowledge
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int insert(Knowledge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_knowledge
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int insertSelective(Knowledge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_knowledge
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    List<Knowledge> selectByExampleWithBLOBs(KnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_knowledge
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    List<Knowledge> selectByExample(KnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_knowledge
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    Knowledge selectByPrimaryKey(String knowledgeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_knowledge
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByExampleSelective(@Param("record") Knowledge record, @Param("example") KnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_knowledge
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") Knowledge record, @Param("example") KnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_knowledge
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByExample(@Param("record") Knowledge record, @Param("example") KnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_knowledge
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByPrimaryKeySelective(Knowledge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_knowledge
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(Knowledge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_knowledge
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByPrimaryKey(Knowledge record);
}