package com.liurq.server.dao;

import com.liurq.server.model.Illness;
import com.liurq.server.model.Major;
import com.liurq.server.model.MajorExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface MajorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_major
     *
     * @mbggenerated Thu Apr 01 16:55:49 CST 2021
     */
    int countByExample(MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_major
     *
     * @mbggenerated Thu Apr 01 16:55:49 CST 2021
     */
    int deleteByExample(MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_major
     *
     * @mbggenerated Thu Apr 01 16:55:49 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_major
     *
     * @mbggenerated Thu Apr 01 16:55:49 CST 2021
     */
    int insert(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_major
     *
     * @mbggenerated Thu Apr 01 16:55:49 CST 2021
     */
    int insertSelective(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_major
     *
     * @mbggenerated Thu Apr 01 16:55:49 CST 2021
     */
    List<Major> selectByExample(MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_major
     *
     * @mbggenerated Thu Apr 01 16:55:49 CST 2021
     */
    Major selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_major
     *
     * @mbggenerated Thu Apr 01 16:55:49 CST 2021
     */
    int updateByExampleSelective(@Param("record") Major record, @Param("example") MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_major
     *
     * @mbggenerated Thu Apr 01 16:55:49 CST 2021
     */
    int updateByExample(@Param("record") Major record, @Param("example") MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_major
     *
     * @mbggenerated Thu Apr 01 16:55:49 CST 2021
     */
    int updateByPrimaryKeySelective(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_major
     *
     * @mbggenerated Thu Apr 01 16:55:49 CST 2021
     */
    int updateByPrimaryKey(Major record);

    /**
     * 查询医生的主攻方向
     * @param doctorId
     * @return
     */
    List<Illness> selectDoctorMajorByDoctorId(String doctorId);

    /**
     * 删除医生的主攻
     * @return
     */
    int deleteDoctorMajors(Map<String,Object> param);
}