package com.liurq.server.dao;

import com.liurq.server.model.Member;
import com.liurq.server.model.MemberExample;
import java.util.List;

import com.liurq.server.restful.rsp.hospital.MemberInfoRsp;
import org.apache.ibatis.annotations.Param;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    int countByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    int deleteByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    int deleteByPrimaryKey(String memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    List<Member> selectByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    Member selectByPrimaryKey(String memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    int updateByExampleSelective(@Param("record") Member record, @Param("example") MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    int updateByExample(@Param("record") Member record, @Param("example") MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    int updateByPrimaryKeySelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    int updateByPrimaryKey(Member record);

    /**
     * 根据用户名搜索用户信息
     * @param username
     * @return
     */
    Member selectByUserName(String username);

    /**
     * 查询子账号信息
     * @param memberId
     * @return
     */
    List<MemberInfoRsp> selectHospitalChildMember(String memberId);

    /**
     * 更新用户的状态
     * @param memberId
     * @param status
     * @return
     */
    int updateMemberStatus(String memberId,String status);
}