package com.liurq.server.dao;

import com.liurq.server.model.TownShip;
import com.liurq.server.model.TownShipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TownShipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_town_ship
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    int countByExample(TownShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_town_ship
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    int deleteByExample(TownShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_town_ship
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_town_ship
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    int insert(TownShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_town_ship
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    int insertSelective(TownShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_town_ship
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    List<TownShip> selectByExample(TownShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_town_ship
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    TownShip selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_town_ship
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    int updateByExampleSelective(@Param("record") TownShip record, @Param("example") TownShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_town_ship
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    int updateByExample(@Param("record") TownShip record, @Param("example") TownShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_town_ship
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    int updateByPrimaryKeySelective(TownShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_town_ship
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    int updateByPrimaryKey(TownShip record);
}