package com.liurq.server.dao;

import com.liurq.server.model.UserRegistration;
import com.liurq.server.model.UserRegistrationExample;
import java.util.List;

import com.liurq.server.restful.rsp.reg.RegistrationListRsp;
import com.liurq.server.restful.rsp.reg.VisitItem;
import org.apache.ibatis.annotations.Param;

public interface UserRegistrationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_registration
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    int countByExample(UserRegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_registration
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    int deleteByExample(UserRegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_registration
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_registration
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    int insert(UserRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_registration
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    int insertSelective(UserRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_registration
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    List<UserRegistration> selectByExample(UserRegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_registration
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    UserRegistration selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_registration
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserRegistration record, @Param("example") UserRegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_registration
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    int updateByExample(@Param("record") UserRegistration record, @Param("example") UserRegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_registration
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    int updateByPrimaryKeySelective(UserRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_registration
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    int updateByPrimaryKey(UserRegistration record);

    /**
     * 查询用户下的挂号历史
     * @param userId
     * @return
     */
    List<RegistrationListRsp> selectRegistrationList(String userId);

    /**
     * 更新用户号的状态
     * @param regId
     * @param status
     * @return
     */
    int updateRegStatus(String regId,String status,String remark);

    /**
     * 更新所有出诊下的号
     * @param visitId
     * @return
     */
    int updateAllRegStatus(String visitId,String status);

    /**
     * 查询当前叫号的id
     * @param visitId
     * @param num
     * @return
     */
    UserRegistration selectNowRegId(String visitId,int num);

    /**
     * 查询下一个叫号的id
     * @param visitId
     * @param num
     * @return
     */
    UserRegistration selectNextRegId(String visitId,int num);

    /**
     * 查询挂号情况
     * @param visitId
     * @return
     */
    List<VisitItem> selectRegList(String visitId);
}