spring:
  redis:
    host: localhost
  application:
    name: common-redis
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      #defaultZone: http://47.99.164.233:8761/eureka
      defaultZone: http://localhost:8761/eureka
key:
  redis:
    person:
      authcode: "person::authcode:"
      authToken: "person::token:"
