package com.liurq.server.model;

import java.util.Date;

public class Patient {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_patient.patient_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_patient.patient_id_card
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String patientIdCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_patient.patient_name
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_patient.patient_sex
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String patientSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_patient.patient_parent_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String patientParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_patient.patient_phone
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String patientPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_patient.patient_address
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String patientAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_patient.patient_relation
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String patientRelation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_patient.patient_image
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String patientImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_patient.patient_birthday
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private Date patientBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_patient.create_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_patient.update_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_patient.status
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_patient.bak_code1
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String bakCode1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_patient.bak_code2
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String bakCode2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_patient.patient_id
     *
     * @return the value of tb_user_patient.patient_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_patient.patient_id
     *
     * @param patientId the value for tb_user_patient.patient_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_patient.patient_id_card
     *
     * @return the value of tb_user_patient.patient_id_card
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getPatientIdCard() {
        return patientIdCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_patient.patient_id_card
     *
     * @param patientIdCard the value for tb_user_patient.patient_id_card
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setPatientIdCard(String patientIdCard) {
        this.patientIdCard = patientIdCard == null ? null : patientIdCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_patient.patient_name
     *
     * @return the value of tb_user_patient.patient_name
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_patient.patient_name
     *
     * @param patientName the value for tb_user_patient.patient_name
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName == null ? null : patientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_patient.patient_sex
     *
     * @return the value of tb_user_patient.patient_sex
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getPatientSex() {
        return patientSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_patient.patient_sex
     *
     * @param patientSex the value for tb_user_patient.patient_sex
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setPatientSex(String patientSex) {
        this.patientSex = patientSex == null ? null : patientSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_patient.patient_parent_id
     *
     * @return the value of tb_user_patient.patient_parent_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getPatientParentId() {
        return patientParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_patient.patient_parent_id
     *
     * @param patientParentId the value for tb_user_patient.patient_parent_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setPatientParentId(String patientParentId) {
        this.patientParentId = patientParentId == null ? null : patientParentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_patient.patient_phone
     *
     * @return the value of tb_user_patient.patient_phone
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getPatientPhone() {
        return patientPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_patient.patient_phone
     *
     * @param patientPhone the value for tb_user_patient.patient_phone
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setPatientPhone(String patientPhone) {
        this.patientPhone = patientPhone == null ? null : patientPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_patient.patient_address
     *
     * @return the value of tb_user_patient.patient_address
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getPatientAddress() {
        return patientAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_patient.patient_address
     *
     * @param patientAddress the value for tb_user_patient.patient_address
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setPatientAddress(String patientAddress) {
        this.patientAddress = patientAddress == null ? null : patientAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_patient.patient_relation
     *
     * @return the value of tb_user_patient.patient_relation
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getPatientRelation() {
        return patientRelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_patient.patient_relation
     *
     * @param patientRelation the value for tb_user_patient.patient_relation
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setPatientRelation(String patientRelation) {
        this.patientRelation = patientRelation == null ? null : patientRelation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_patient.patient_image
     *
     * @return the value of tb_user_patient.patient_image
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getPatientImage() {
        return patientImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_patient.patient_image
     *
     * @param patientImage the value for tb_user_patient.patient_image
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setPatientImage(String patientImage) {
        this.patientImage = patientImage == null ? null : patientImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_patient.patient_birthday
     *
     * @return the value of tb_user_patient.patient_birthday
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public Date getPatientBirthday() {
        return patientBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_patient.patient_birthday
     *
     * @param patientBirthday the value for tb_user_patient.patient_birthday
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setPatientBirthday(Date patientBirthday) {
        this.patientBirthday = patientBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_patient.create_date
     *
     * @return the value of tb_user_patient.create_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_patient.create_date
     *
     * @param createDate the value for tb_user_patient.create_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_patient.update_date
     *
     * @return the value of tb_user_patient.update_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_patient.update_date
     *
     * @param updateDate the value for tb_user_patient.update_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_patient.status
     *
     * @return the value of tb_user_patient.status
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_patient.status
     *
     * @param status the value for tb_user_patient.status
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_patient.bak_code1
     *
     * @return the value of tb_user_patient.bak_code1
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getBakCode1() {
        return bakCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_patient.bak_code1
     *
     * @param bakCode1 the value for tb_user_patient.bak_code1
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setBakCode1(String bakCode1) {
        this.bakCode1 = bakCode1 == null ? null : bakCode1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_patient.bak_code2
     *
     * @return the value of tb_user_patient.bak_code2
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getBakCode2() {
        return bakCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_patient.bak_code2
     *
     * @param bakCode2 the value for tb_user_patient.bak_code2
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setBakCode2(String bakCode2) {
        this.bakCode2 = bakCode2 == null ? null : bakCode2.trim();
    }
}