package com.liurq.server.model;

import java.util.Date;

public class Tag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_tag.tag_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_tag.tag_name
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_tag.deleted
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_tag.create_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_tag.update_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_tag.tag_id
     *
     * @return the value of td_tag.tag_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_tag.tag_id
     *
     * @param tagId the value for td_tag.tag_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setTagId(String tagId) {
        this.tagId = tagId == null ? null : tagId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_tag.tag_name
     *
     * @return the value of td_tag.tag_name
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_tag.tag_name
     *
     * @param tagName the value for td_tag.tag_name
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_tag.deleted
     *
     * @return the value of td_tag.deleted
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_tag.deleted
     *
     * @param deleted the value for td_tag.deleted
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_tag.create_date
     *
     * @return the value of td_tag.create_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_tag.create_date
     *
     * @param createDate the value for td_tag.create_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_tag.update_date
     *
     * @return the value of td_tag.update_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_tag.update_date
     *
     * @param updateDate the value for td_tag.update_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}