package com.liurq.server.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user_log
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user_log
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user_log
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public UserLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_user_log
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLogIdIsNull() {
            addCriterion("log_id is null");
            return (Criteria) this;
        }

        public Criteria andLogIdIsNotNull() {
            addCriterion("log_id is not null");
            return (Criteria) this;
        }

        public Criteria andLogIdEqualTo(String value) {
            addCriterion("log_id =", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotEqualTo(String value) {
            addCriterion("log_id <>", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdGreaterThan(String value) {
            addCriterion("log_id >", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdGreaterThanOrEqualTo(String value) {
            addCriterion("log_id >=", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdLessThan(String value) {
            addCriterion("log_id <", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdLessThanOrEqualTo(String value) {
            addCriterion("log_id <=", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdLike(String value) {
            addCriterion("log_id like", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotLike(String value) {
            addCriterion("log_id not like", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdIn(List<String> values) {
            addCriterion("log_id in", values, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotIn(List<String> values) {
            addCriterion("log_id not in", values, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdBetween(String value1, String value2) {
            addCriterion("log_id between", value1, value2, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotBetween(String value1, String value2) {
            addCriterion("log_id not between", value1, value2, "logId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andOperationNameIsNull() {
            addCriterion("operation_name is null");
            return (Criteria) this;
        }

        public Criteria andOperationNameIsNotNull() {
            addCriterion("operation_name is not null");
            return (Criteria) this;
        }

        public Criteria andOperationNameEqualTo(String value) {
            addCriterion("operation_name =", value, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameNotEqualTo(String value) {
            addCriterion("operation_name <>", value, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameGreaterThan(String value) {
            addCriterion("operation_name >", value, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameGreaterThanOrEqualTo(String value) {
            addCriterion("operation_name >=", value, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameLessThan(String value) {
            addCriterion("operation_name <", value, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameLessThanOrEqualTo(String value) {
            addCriterion("operation_name <=", value, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameLike(String value) {
            addCriterion("operation_name like", value, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameNotLike(String value) {
            addCriterion("operation_name not like", value, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameIn(List<String> values) {
            addCriterion("operation_name in", values, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameNotIn(List<String> values) {
            addCriterion("operation_name not in", values, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameBetween(String value1, String value2) {
            addCriterion("operation_name between", value1, value2, "operationName");
            return (Criteria) this;
        }

        public Criteria andOperationNameNotBetween(String value1, String value2) {
            addCriterion("operation_name not between", value1, value2, "operationName");
            return (Criteria) this;
        }

        public Criteria andRelIdIsNull() {
            addCriterion("rel_id is null");
            return (Criteria) this;
        }

        public Criteria andRelIdIsNotNull() {
            addCriterion("rel_id is not null");
            return (Criteria) this;
        }

        public Criteria andRelIdEqualTo(String value) {
            addCriterion("rel_id =", value, "relId");
            return (Criteria) this;
        }

        public Criteria andRelIdNotEqualTo(String value) {
            addCriterion("rel_id <>", value, "relId");
            return (Criteria) this;
        }

        public Criteria andRelIdGreaterThan(String value) {
            addCriterion("rel_id >", value, "relId");
            return (Criteria) this;
        }

        public Criteria andRelIdGreaterThanOrEqualTo(String value) {
            addCriterion("rel_id >=", value, "relId");
            return (Criteria) this;
        }

        public Criteria andRelIdLessThan(String value) {
            addCriterion("rel_id <", value, "relId");
            return (Criteria) this;
        }

        public Criteria andRelIdLessThanOrEqualTo(String value) {
            addCriterion("rel_id <=", value, "relId");
            return (Criteria) this;
        }

        public Criteria andRelIdLike(String value) {
            addCriterion("rel_id like", value, "relId");
            return (Criteria) this;
        }

        public Criteria andRelIdNotLike(String value) {
            addCriterion("rel_id not like", value, "relId");
            return (Criteria) this;
        }

        public Criteria andRelIdIn(List<String> values) {
            addCriterion("rel_id in", values, "relId");
            return (Criteria) this;
        }

        public Criteria andRelIdNotIn(List<String> values) {
            addCriterion("rel_id not in", values, "relId");
            return (Criteria) this;
        }

        public Criteria andRelIdBetween(String value1, String value2) {
            addCriterion("rel_id between", value1, value2, "relId");
            return (Criteria) this;
        }

        public Criteria andRelIdNotBetween(String value1, String value2) {
            addCriterion("rel_id not between", value1, value2, "relId");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andBakCode1IsNull() {
            addCriterion("bak_code1 is null");
            return (Criteria) this;
        }

        public Criteria andBakCode1IsNotNull() {
            addCriterion("bak_code1 is not null");
            return (Criteria) this;
        }

        public Criteria andBakCode1EqualTo(String value) {
            addCriterion("bak_code1 =", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1NotEqualTo(String value) {
            addCriterion("bak_code1 <>", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1GreaterThan(String value) {
            addCriterion("bak_code1 >", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1GreaterThanOrEqualTo(String value) {
            addCriterion("bak_code1 >=", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1LessThan(String value) {
            addCriterion("bak_code1 <", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1LessThanOrEqualTo(String value) {
            addCriterion("bak_code1 <=", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1Like(String value) {
            addCriterion("bak_code1 like", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1NotLike(String value) {
            addCriterion("bak_code1 not like", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1In(List<String> values) {
            addCriterion("bak_code1 in", values, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1NotIn(List<String> values) {
            addCriterion("bak_code1 not in", values, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1Between(String value1, String value2) {
            addCriterion("bak_code1 between", value1, value2, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1NotBetween(String value1, String value2) {
            addCriterion("bak_code1 not between", value1, value2, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode2IsNull() {
            addCriterion("bak_code2 is null");
            return (Criteria) this;
        }

        public Criteria andBakCode2IsNotNull() {
            addCriterion("bak_code2 is not null");
            return (Criteria) this;
        }

        public Criteria andBakCode2EqualTo(String value) {
            addCriterion("bak_code2 =", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2NotEqualTo(String value) {
            addCriterion("bak_code2 <>", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2GreaterThan(String value) {
            addCriterion("bak_code2 >", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2GreaterThanOrEqualTo(String value) {
            addCriterion("bak_code2 >=", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2LessThan(String value) {
            addCriterion("bak_code2 <", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2LessThanOrEqualTo(String value) {
            addCriterion("bak_code2 <=", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2Like(String value) {
            addCriterion("bak_code2 like", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2NotLike(String value) {
            addCriterion("bak_code2 not like", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2In(List<String> values) {
            addCriterion("bak_code2 in", values, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2NotIn(List<String> values) {
            addCriterion("bak_code2 not in", values, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2Between(String value1, String value2) {
            addCriterion("bak_code2 between", value1, value2, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2NotBetween(String value1, String value2) {
            addCriterion("bak_code2 not between", value1, value2, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode3IsNull() {
            addCriterion("bak_code3 is null");
            return (Criteria) this;
        }

        public Criteria andBakCode3IsNotNull() {
            addCriterion("bak_code3 is not null");
            return (Criteria) this;
        }

        public Criteria andBakCode3EqualTo(String value) {
            addCriterion("bak_code3 =", value, "bakCode3");
            return (Criteria) this;
        }

        public Criteria andBakCode3NotEqualTo(String value) {
            addCriterion("bak_code3 <>", value, "bakCode3");
            return (Criteria) this;
        }

        public Criteria andBakCode3GreaterThan(String value) {
            addCriterion("bak_code3 >", value, "bakCode3");
            return (Criteria) this;
        }

        public Criteria andBakCode3GreaterThanOrEqualTo(String value) {
            addCriterion("bak_code3 >=", value, "bakCode3");
            return (Criteria) this;
        }

        public Criteria andBakCode3LessThan(String value) {
            addCriterion("bak_code3 <", value, "bakCode3");
            return (Criteria) this;
        }

        public Criteria andBakCode3LessThanOrEqualTo(String value) {
            addCriterion("bak_code3 <=", value, "bakCode3");
            return (Criteria) this;
        }

        public Criteria andBakCode3Like(String value) {
            addCriterion("bak_code3 like", value, "bakCode3");
            return (Criteria) this;
        }

        public Criteria andBakCode3NotLike(String value) {
            addCriterion("bak_code3 not like", value, "bakCode3");
            return (Criteria) this;
        }

        public Criteria andBakCode3In(List<String> values) {
            addCriterion("bak_code3 in", values, "bakCode3");
            return (Criteria) this;
        }

        public Criteria andBakCode3NotIn(List<String> values) {
            addCriterion("bak_code3 not in", values, "bakCode3");
            return (Criteria) this;
        }

        public Criteria andBakCode3Between(String value1, String value2) {
            addCriterion("bak_code3 between", value1, value2, "bakCode3");
            return (Criteria) this;
        }

        public Criteria andBakCode3NotBetween(String value1, String value2) {
            addCriterion("bak_code3 not between", value1, value2, "bakCode3");
            return (Criteria) this;
        }

        public Criteria andBakCode4IsNull() {
            addCriterion("bak_code4 is null");
            return (Criteria) this;
        }

        public Criteria andBakCode4IsNotNull() {
            addCriterion("bak_code4 is not null");
            return (Criteria) this;
        }

        public Criteria andBakCode4EqualTo(String value) {
            addCriterion("bak_code4 =", value, "bakCode4");
            return (Criteria) this;
        }

        public Criteria andBakCode4NotEqualTo(String value) {
            addCriterion("bak_code4 <>", value, "bakCode4");
            return (Criteria) this;
        }

        public Criteria andBakCode4GreaterThan(String value) {
            addCriterion("bak_code4 >", value, "bakCode4");
            return (Criteria) this;
        }

        public Criteria andBakCode4GreaterThanOrEqualTo(String value) {
            addCriterion("bak_code4 >=", value, "bakCode4");
            return (Criteria) this;
        }

        public Criteria andBakCode4LessThan(String value) {
            addCriterion("bak_code4 <", value, "bakCode4");
            return (Criteria) this;
        }

        public Criteria andBakCode4LessThanOrEqualTo(String value) {
            addCriterion("bak_code4 <=", value, "bakCode4");
            return (Criteria) this;
        }

        public Criteria andBakCode4Like(String value) {
            addCriterion("bak_code4 like", value, "bakCode4");
            return (Criteria) this;
        }

        public Criteria andBakCode4NotLike(String value) {
            addCriterion("bak_code4 not like", value, "bakCode4");
            return (Criteria) this;
        }

        public Criteria andBakCode4In(List<String> values) {
            addCriterion("bak_code4 in", values, "bakCode4");
            return (Criteria) this;
        }

        public Criteria andBakCode4NotIn(List<String> values) {
            addCriterion("bak_code4 not in", values, "bakCode4");
            return (Criteria) this;
        }

        public Criteria andBakCode4Between(String value1, String value2) {
            addCriterion("bak_code4 between", value1, value2, "bakCode4");
            return (Criteria) this;
        }

        public Criteria andBakCode4NotBetween(String value1, String value2) {
            addCriterion("bak_code4 not between", value1, value2, "bakCode4");
            return (Criteria) this;
        }

        public Criteria andBakCode5IsNull() {
            addCriterion("bak_code5 is null");
            return (Criteria) this;
        }

        public Criteria andBakCode5IsNotNull() {
            addCriterion("bak_code5 is not null");
            return (Criteria) this;
        }

        public Criteria andBakCode5EqualTo(String value) {
            addCriterion("bak_code5 =", value, "bakCode5");
            return (Criteria) this;
        }

        public Criteria andBakCode5NotEqualTo(String value) {
            addCriterion("bak_code5 <>", value, "bakCode5");
            return (Criteria) this;
        }

        public Criteria andBakCode5GreaterThan(String value) {
            addCriterion("bak_code5 >", value, "bakCode5");
            return (Criteria) this;
        }

        public Criteria andBakCode5GreaterThanOrEqualTo(String value) {
            addCriterion("bak_code5 >=", value, "bakCode5");
            return (Criteria) this;
        }

        public Criteria andBakCode5LessThan(String value) {
            addCriterion("bak_code5 <", value, "bakCode5");
            return (Criteria) this;
        }

        public Criteria andBakCode5LessThanOrEqualTo(String value) {
            addCriterion("bak_code5 <=", value, "bakCode5");
            return (Criteria) this;
        }

        public Criteria andBakCode5Like(String value) {
            addCriterion("bak_code5 like", value, "bakCode5");
            return (Criteria) this;
        }

        public Criteria andBakCode5NotLike(String value) {
            addCriterion("bak_code5 not like", value, "bakCode5");
            return (Criteria) this;
        }

        public Criteria andBakCode5In(List<String> values) {
            addCriterion("bak_code5 in", values, "bakCode5");
            return (Criteria) this;
        }

        public Criteria andBakCode5NotIn(List<String> values) {
            addCriterion("bak_code5 not in", values, "bakCode5");
            return (Criteria) this;
        }

        public Criteria andBakCode5Between(String value1, String value2) {
            addCriterion("bak_code5 between", value1, value2, "bakCode5");
            return (Criteria) this;
        }

        public Criteria andBakCode5NotBetween(String value1, String value2) {
            addCriterion("bak_code5 not between", value1, value2, "bakCode5");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(String value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(String value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(String value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(String value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(String value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLike(String value) {
            addCriterion("deleted like", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotLike(String value) {
            addCriterion("deleted not like", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<String> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<String> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(String value1, String value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(String value1, String value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_user_log
     *
     * @mbggenerated do_not_delete_during_merge Wed Feb 03 19:23:50 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_user_log
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}