package com.liurq.server.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_name
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_sex
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_phone
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_image
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String userImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_address
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_id_card
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String userIdCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_password
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_birthday
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private Date userBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.create_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.update_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.status
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.bak_code1
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String bakCode1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.bak_code2
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String bakCode2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_id
     *
     * @return the value of tb_user.user_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_id
     *
     * @param userId the value for tb_user.user_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_name
     *
     * @return the value of tb_user.user_name
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_name
     *
     * @param userName the value for tb_user.user_name
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_sex
     *
     * @return the value of tb_user.user_sex
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_sex
     *
     * @param userSex the value for tb_user.user_sex
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex == null ? null : userSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_phone
     *
     * @return the value of tb_user.user_phone
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_phone
     *
     * @param userPhone the value for tb_user.user_phone
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_image
     *
     * @return the value of tb_user.user_image
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getUserImage() {
        return userImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_image
     *
     * @param userImage the value for tb_user.user_image
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setUserImage(String userImage) {
        this.userImage = userImage == null ? null : userImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_address
     *
     * @return the value of tb_user.user_address
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_address
     *
     * @param userAddress the value for tb_user.user_address
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_id_card
     *
     * @return the value of tb_user.user_id_card
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getUserIdCard() {
        return userIdCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_id_card
     *
     * @param userIdCard the value for tb_user.user_id_card
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setUserIdCard(String userIdCard) {
        this.userIdCard = userIdCard == null ? null : userIdCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_password
     *
     * @return the value of tb_user.user_password
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_password
     *
     * @param userPassword the value for tb_user.user_password
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_birthday
     *
     * @return the value of tb_user.user_birthday
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_birthday
     *
     * @param userBirthday the value for tb_user.user_birthday
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.create_date
     *
     * @return the value of tb_user.create_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.create_date
     *
     * @param createDate the value for tb_user.create_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.update_date
     *
     * @return the value of tb_user.update_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.update_date
     *
     * @param updateDate the value for tb_user.update_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.status
     *
     * @return the value of tb_user.status
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.status
     *
     * @param status the value for tb_user.status
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.bak_code1
     *
     * @return the value of tb_user.bak_code1
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getBakCode1() {
        return bakCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.bak_code1
     *
     * @param bakCode1 the value for tb_user.bak_code1
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setBakCode1(String bakCode1) {
        this.bakCode1 = bakCode1 == null ? null : bakCode1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.bak_code2
     *
     * @return the value of tb_user.bak_code2
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getBakCode2() {
        return bakCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.bak_code2
     *
     * @param bakCode2 the value for tb_user.bak_code2
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setBakCode2(String bakCode2) {
        this.bakCode2 = bakCode2 == null ? null : bakCode2.trim();
    }
}