package com.liurq.server.model;

import java.util.Date;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.department_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.department_name
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.department_image
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String departmentImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.create_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.update_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.status
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.bak_code1
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String bakCode1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.bak_code2
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String bakCode2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.department_id
     *
     * @return the value of tb_department.department_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.department_id
     *
     * @param departmentId the value for tb_department.department_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.department_name
     *
     * @return the value of tb_department.department_name
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.department_name
     *
     * @param departmentName the value for tb_department.department_name
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.department_image
     *
     * @return the value of tb_department.department_image
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getDepartmentImage() {
        return departmentImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.department_image
     *
     * @param departmentImage the value for tb_department.department_image
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setDepartmentImage(String departmentImage) {
        this.departmentImage = departmentImage == null ? null : departmentImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.create_date
     *
     * @return the value of tb_department.create_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.create_date
     *
     * @param createDate the value for tb_department.create_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.update_date
     *
     * @return the value of tb_department.update_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.update_date
     *
     * @param updateDate the value for tb_department.update_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.status
     *
     * @return the value of tb_department.status
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.status
     *
     * @param status the value for tb_department.status
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.bak_code1
     *
     * @return the value of tb_department.bak_code1
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getBakCode1() {
        return bakCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.bak_code1
     *
     * @param bakCode1 the value for tb_department.bak_code1
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setBakCode1(String bakCode1) {
        this.bakCode1 = bakCode1 == null ? null : bakCode1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.bak_code2
     *
     * @return the value of tb_department.bak_code2
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getBakCode2() {
        return bakCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.bak_code2
     *
     * @param bakCode2 the value for tb_department.bak_code2
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setBakCode2(String bakCode2) {
        this.bakCode2 = bakCode2 == null ? null : bakCode2.trim();
    }
}