package com.liurq.server.model;

import java.util.Date;

public class Doctor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.doctor_id
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    private String doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.doctor_name
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    private String doctorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.doctor_sex
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    private String doctorSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.doctor_work_age
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    private Integer doctorWorkAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.doctor_level
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    private String doctorLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.doctor_feedback_rate
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    private String doctorFeedbackRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.doctor_registration_count
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    private Integer doctorRegistrationCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.doctor_image
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    private String doctorImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.doctor_phone
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    private String doctorPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.status
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.create_date
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.update_date
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.remark
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.doctor_id
     *
     * @return the value of tb_doctor.doctor_id
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.doctor_id
     *
     * @param doctorId the value for tb_doctor.doctor_id
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId == null ? null : doctorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.doctor_name
     *
     * @return the value of tb_doctor.doctor_name
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.doctor_name
     *
     * @param doctorName the value for tb_doctor.doctor_name
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.doctor_sex
     *
     * @return the value of tb_doctor.doctor_sex
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public String getDoctorSex() {
        return doctorSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.doctor_sex
     *
     * @param doctorSex the value for tb_doctor.doctor_sex
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public void setDoctorSex(String doctorSex) {
        this.doctorSex = doctorSex == null ? null : doctorSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.doctor_work_age
     *
     * @return the value of tb_doctor.doctor_work_age
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public Integer getDoctorWorkAge() {
        return doctorWorkAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.doctor_work_age
     *
     * @param doctorWorkAge the value for tb_doctor.doctor_work_age
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public void setDoctorWorkAge(Integer doctorWorkAge) {
        this.doctorWorkAge = doctorWorkAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.doctor_level
     *
     * @return the value of tb_doctor.doctor_level
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public String getDoctorLevel() {
        return doctorLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.doctor_level
     *
     * @param doctorLevel the value for tb_doctor.doctor_level
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public void setDoctorLevel(String doctorLevel) {
        this.doctorLevel = doctorLevel == null ? null : doctorLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.doctor_feedback_rate
     *
     * @return the value of tb_doctor.doctor_feedback_rate
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public String getDoctorFeedbackRate() {
        return doctorFeedbackRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.doctor_feedback_rate
     *
     * @param doctorFeedbackRate the value for tb_doctor.doctor_feedback_rate
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public void setDoctorFeedbackRate(String doctorFeedbackRate) {
        this.doctorFeedbackRate = doctorFeedbackRate == null ? null : doctorFeedbackRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.doctor_registration_count
     *
     * @return the value of tb_doctor.doctor_registration_count
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public Integer getDoctorRegistrationCount() {
        return doctorRegistrationCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.doctor_registration_count
     *
     * @param doctorRegistrationCount the value for tb_doctor.doctor_registration_count
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public void setDoctorRegistrationCount(Integer doctorRegistrationCount) {
        this.doctorRegistrationCount = doctorRegistrationCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.doctor_image
     *
     * @return the value of tb_doctor.doctor_image
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public String getDoctorImage() {
        return doctorImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.doctor_image
     *
     * @param doctorImage the value for tb_doctor.doctor_image
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public void setDoctorImage(String doctorImage) {
        this.doctorImage = doctorImage == null ? null : doctorImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.doctor_phone
     *
     * @return the value of tb_doctor.doctor_phone
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public String getDoctorPhone() {
        return doctorPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.doctor_phone
     *
     * @param doctorPhone the value for tb_doctor.doctor_phone
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public void setDoctorPhone(String doctorPhone) {
        this.doctorPhone = doctorPhone == null ? null : doctorPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.status
     *
     * @return the value of tb_doctor.status
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.status
     *
     * @param status the value for tb_doctor.status
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.create_date
     *
     * @return the value of tb_doctor.create_date
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.create_date
     *
     * @param createDate the value for tb_doctor.create_date
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.update_date
     *
     * @return the value of tb_doctor.update_date
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.update_date
     *
     * @param updateDate the value for tb_doctor.update_date
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.remark
     *
     * @return the value of tb_doctor.remark
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.remark
     *
     * @param remark the value for tb_doctor.remark
     *
     * @mbggenerated Fri Feb 26 14:46:47 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}