package com.liurq.server.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HospitalExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_hospital
     *
     * @mbggenerated Sat Feb 13 18:45:57 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_hospital
     *
     * @mbggenerated Sat Feb 13 18:45:57 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_hospital
     *
     * @mbggenerated Sat Feb 13 18:45:57 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sat Feb 13 18:45:57 CST 2021
     */
    public HospitalExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sat Feb 13 18:45:57 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sat Feb 13 18:45:57 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sat Feb 13 18:45:57 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sat Feb 13 18:45:57 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sat Feb 13 18:45:57 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sat Feb 13 18:45:57 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sat Feb 13 18:45:57 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sat Feb 13 18:45:57 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sat Feb 13 18:45:57 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Sat Feb 13 18:45:57 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_hospital
     *
     * @mbggenerated Sat Feb 13 18:45:57 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHospitalIdIsNull() {
            addCriterion("hospital_id is null");
            return (Criteria) this;
        }

        public Criteria andHospitalIdIsNotNull() {
            addCriterion("hospital_id is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalIdEqualTo(String value) {
            addCriterion("hospital_id =", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdNotEqualTo(String value) {
            addCriterion("hospital_id <>", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdGreaterThan(String value) {
            addCriterion("hospital_id >", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_id >=", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdLessThan(String value) {
            addCriterion("hospital_id <", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdLessThanOrEqualTo(String value) {
            addCriterion("hospital_id <=", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdLike(String value) {
            addCriterion("hospital_id like", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdNotLike(String value) {
            addCriterion("hospital_id not like", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdIn(List<String> values) {
            addCriterion("hospital_id in", values, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdNotIn(List<String> values) {
            addCriterion("hospital_id not in", values, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdBetween(String value1, String value2) {
            addCriterion("hospital_id between", value1, value2, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdNotBetween(String value1, String value2) {
            addCriterion("hospital_id not between", value1, value2, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalNameIsNull() {
            addCriterion("hospital_name is null");
            return (Criteria) this;
        }

        public Criteria andHospitalNameIsNotNull() {
            addCriterion("hospital_name is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalNameEqualTo(String value) {
            addCriterion("hospital_name =", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameNotEqualTo(String value) {
            addCriterion("hospital_name <>", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameGreaterThan(String value) {
            addCriterion("hospital_name >", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_name >=", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameLessThan(String value) {
            addCriterion("hospital_name <", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameLessThanOrEqualTo(String value) {
            addCriterion("hospital_name <=", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameLike(String value) {
            addCriterion("hospital_name like", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameNotLike(String value) {
            addCriterion("hospital_name not like", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameIn(List<String> values) {
            addCriterion("hospital_name in", values, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameNotIn(List<String> values) {
            addCriterion("hospital_name not in", values, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameBetween(String value1, String value2) {
            addCriterion("hospital_name between", value1, value2, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameNotBetween(String value1, String value2) {
            addCriterion("hospital_name not between", value1, value2, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressIsNull() {
            addCriterion("hospital_address is null");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressIsNotNull() {
            addCriterion("hospital_address is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressEqualTo(String value) {
            addCriterion("hospital_address =", value, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressNotEqualTo(String value) {
            addCriterion("hospital_address <>", value, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressGreaterThan(String value) {
            addCriterion("hospital_address >", value, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_address >=", value, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressLessThan(String value) {
            addCriterion("hospital_address <", value, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressLessThanOrEqualTo(String value) {
            addCriterion("hospital_address <=", value, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressLike(String value) {
            addCriterion("hospital_address like", value, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressNotLike(String value) {
            addCriterion("hospital_address not like", value, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressIn(List<String> values) {
            addCriterion("hospital_address in", values, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressNotIn(List<String> values) {
            addCriterion("hospital_address not in", values, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressBetween(String value1, String value2) {
            addCriterion("hospital_address between", value1, value2, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressNotBetween(String value1, String value2) {
            addCriterion("hospital_address not between", value1, value2, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalCityIsNull() {
            addCriterion("hospital_city is null");
            return (Criteria) this;
        }

        public Criteria andHospitalCityIsNotNull() {
            addCriterion("hospital_city is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalCityEqualTo(String value) {
            addCriterion("hospital_city =", value, "hospitalCity");
            return (Criteria) this;
        }

        public Criteria andHospitalCityNotEqualTo(String value) {
            addCriterion("hospital_city <>", value, "hospitalCity");
            return (Criteria) this;
        }

        public Criteria andHospitalCityGreaterThan(String value) {
            addCriterion("hospital_city >", value, "hospitalCity");
            return (Criteria) this;
        }

        public Criteria andHospitalCityGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_city >=", value, "hospitalCity");
            return (Criteria) this;
        }

        public Criteria andHospitalCityLessThan(String value) {
            addCriterion("hospital_city <", value, "hospitalCity");
            return (Criteria) this;
        }

        public Criteria andHospitalCityLessThanOrEqualTo(String value) {
            addCriterion("hospital_city <=", value, "hospitalCity");
            return (Criteria) this;
        }

        public Criteria andHospitalCityLike(String value) {
            addCriterion("hospital_city like", value, "hospitalCity");
            return (Criteria) this;
        }

        public Criteria andHospitalCityNotLike(String value) {
            addCriterion("hospital_city not like", value, "hospitalCity");
            return (Criteria) this;
        }

        public Criteria andHospitalCityIn(List<String> values) {
            addCriterion("hospital_city in", values, "hospitalCity");
            return (Criteria) this;
        }

        public Criteria andHospitalCityNotIn(List<String> values) {
            addCriterion("hospital_city not in", values, "hospitalCity");
            return (Criteria) this;
        }

        public Criteria andHospitalCityBetween(String value1, String value2) {
            addCriterion("hospital_city between", value1, value2, "hospitalCity");
            return (Criteria) this;
        }

        public Criteria andHospitalCityNotBetween(String value1, String value2) {
            addCriterion("hospital_city not between", value1, value2, "hospitalCity");
            return (Criteria) this;
        }

        public Criteria andHospitalCountryIsNull() {
            addCriterion("hospital_country is null");
            return (Criteria) this;
        }

        public Criteria andHospitalCountryIsNotNull() {
            addCriterion("hospital_country is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalCountryEqualTo(String value) {
            addCriterion("hospital_country =", value, "hospitalCountry");
            return (Criteria) this;
        }

        public Criteria andHospitalCountryNotEqualTo(String value) {
            addCriterion("hospital_country <>", value, "hospitalCountry");
            return (Criteria) this;
        }

        public Criteria andHospitalCountryGreaterThan(String value) {
            addCriterion("hospital_country >", value, "hospitalCountry");
            return (Criteria) this;
        }

        public Criteria andHospitalCountryGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_country >=", value, "hospitalCountry");
            return (Criteria) this;
        }

        public Criteria andHospitalCountryLessThan(String value) {
            addCriterion("hospital_country <", value, "hospitalCountry");
            return (Criteria) this;
        }

        public Criteria andHospitalCountryLessThanOrEqualTo(String value) {
            addCriterion("hospital_country <=", value, "hospitalCountry");
            return (Criteria) this;
        }

        public Criteria andHospitalCountryLike(String value) {
            addCriterion("hospital_country like", value, "hospitalCountry");
            return (Criteria) this;
        }

        public Criteria andHospitalCountryNotLike(String value) {
            addCriterion("hospital_country not like", value, "hospitalCountry");
            return (Criteria) this;
        }

        public Criteria andHospitalCountryIn(List<String> values) {
            addCriterion("hospital_country in", values, "hospitalCountry");
            return (Criteria) this;
        }

        public Criteria andHospitalCountryNotIn(List<String> values) {
            addCriterion("hospital_country not in", values, "hospitalCountry");
            return (Criteria) this;
        }

        public Criteria andHospitalCountryBetween(String value1, String value2) {
            addCriterion("hospital_country between", value1, value2, "hospitalCountry");
            return (Criteria) this;
        }

        public Criteria andHospitalCountryNotBetween(String value1, String value2) {
            addCriterion("hospital_country not between", value1, value2, "hospitalCountry");
            return (Criteria) this;
        }

        public Criteria andHospitalProvinceIsNull() {
            addCriterion("hospital_province is null");
            return (Criteria) this;
        }

        public Criteria andHospitalProvinceIsNotNull() {
            addCriterion("hospital_province is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalProvinceEqualTo(String value) {
            addCriterion("hospital_province =", value, "hospitalProvince");
            return (Criteria) this;
        }

        public Criteria andHospitalProvinceNotEqualTo(String value) {
            addCriterion("hospital_province <>", value, "hospitalProvince");
            return (Criteria) this;
        }

        public Criteria andHospitalProvinceGreaterThan(String value) {
            addCriterion("hospital_province >", value, "hospitalProvince");
            return (Criteria) this;
        }

        public Criteria andHospitalProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_province >=", value, "hospitalProvince");
            return (Criteria) this;
        }

        public Criteria andHospitalProvinceLessThan(String value) {
            addCriterion("hospital_province <", value, "hospitalProvince");
            return (Criteria) this;
        }

        public Criteria andHospitalProvinceLessThanOrEqualTo(String value) {
            addCriterion("hospital_province <=", value, "hospitalProvince");
            return (Criteria) this;
        }

        public Criteria andHospitalProvinceLike(String value) {
            addCriterion("hospital_province like", value, "hospitalProvince");
            return (Criteria) this;
        }

        public Criteria andHospitalProvinceNotLike(String value) {
            addCriterion("hospital_province not like", value, "hospitalProvince");
            return (Criteria) this;
        }

        public Criteria andHospitalProvinceIn(List<String> values) {
            addCriterion("hospital_province in", values, "hospitalProvince");
            return (Criteria) this;
        }

        public Criteria andHospitalProvinceNotIn(List<String> values) {
            addCriterion("hospital_province not in", values, "hospitalProvince");
            return (Criteria) this;
        }

        public Criteria andHospitalProvinceBetween(String value1, String value2) {
            addCriterion("hospital_province between", value1, value2, "hospitalProvince");
            return (Criteria) this;
        }

        public Criteria andHospitalProvinceNotBetween(String value1, String value2) {
            addCriterion("hospital_province not between", value1, value2, "hospitalProvince");
            return (Criteria) this;
        }

        public Criteria andHospitalImageIsNull() {
            addCriterion("hospital_image is null");
            return (Criteria) this;
        }

        public Criteria andHospitalImageIsNotNull() {
            addCriterion("hospital_image is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalImageEqualTo(String value) {
            addCriterion("hospital_image =", value, "hospitalImage");
            return (Criteria) this;
        }

        public Criteria andHospitalImageNotEqualTo(String value) {
            addCriterion("hospital_image <>", value, "hospitalImage");
            return (Criteria) this;
        }

        public Criteria andHospitalImageGreaterThan(String value) {
            addCriterion("hospital_image >", value, "hospitalImage");
            return (Criteria) this;
        }

        public Criteria andHospitalImageGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_image >=", value, "hospitalImage");
            return (Criteria) this;
        }

        public Criteria andHospitalImageLessThan(String value) {
            addCriterion("hospital_image <", value, "hospitalImage");
            return (Criteria) this;
        }

        public Criteria andHospitalImageLessThanOrEqualTo(String value) {
            addCriterion("hospital_image <=", value, "hospitalImage");
            return (Criteria) this;
        }

        public Criteria andHospitalImageLike(String value) {
            addCriterion("hospital_image like", value, "hospitalImage");
            return (Criteria) this;
        }

        public Criteria andHospitalImageNotLike(String value) {
            addCriterion("hospital_image not like", value, "hospitalImage");
            return (Criteria) this;
        }

        public Criteria andHospitalImageIn(List<String> values) {
            addCriterion("hospital_image in", values, "hospitalImage");
            return (Criteria) this;
        }

        public Criteria andHospitalImageNotIn(List<String> values) {
            addCriterion("hospital_image not in", values, "hospitalImage");
            return (Criteria) this;
        }

        public Criteria andHospitalImageBetween(String value1, String value2) {
            addCriterion("hospital_image between", value1, value2, "hospitalImage");
            return (Criteria) this;
        }

        public Criteria andHospitalImageNotBetween(String value1, String value2) {
            addCriterion("hospital_image not between", value1, value2, "hospitalImage");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelIsNull() {
            addCriterion("hospital_level is null");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelIsNotNull() {
            addCriterion("hospital_level is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelEqualTo(String value) {
            addCriterion("hospital_level =", value, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNotEqualTo(String value) {
            addCriterion("hospital_level <>", value, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelGreaterThan(String value) {
            addCriterion("hospital_level >", value, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_level >=", value, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelLessThan(String value) {
            addCriterion("hospital_level <", value, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelLessThanOrEqualTo(String value) {
            addCriterion("hospital_level <=", value, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelLike(String value) {
            addCriterion("hospital_level like", value, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNotLike(String value) {
            addCriterion("hospital_level not like", value, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelIn(List<String> values) {
            addCriterion("hospital_level in", values, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNotIn(List<String> values) {
            addCriterion("hospital_level not in", values, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelBetween(String value1, String value2) {
            addCriterion("hospital_level between", value1, value2, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNotBetween(String value1, String value2) {
            addCriterion("hospital_level not between", value1, value2, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNameIsNull() {
            addCriterion("hospital_level_name is null");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNameIsNotNull() {
            addCriterion("hospital_level_name is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNameEqualTo(String value) {
            addCriterion("hospital_level_name =", value, "hospitalLevelName");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNameNotEqualTo(String value) {
            addCriterion("hospital_level_name <>", value, "hospitalLevelName");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNameGreaterThan(String value) {
            addCriterion("hospital_level_name >", value, "hospitalLevelName");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNameGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_level_name >=", value, "hospitalLevelName");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNameLessThan(String value) {
            addCriterion("hospital_level_name <", value, "hospitalLevelName");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNameLessThanOrEqualTo(String value) {
            addCriterion("hospital_level_name <=", value, "hospitalLevelName");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNameLike(String value) {
            addCriterion("hospital_level_name like", value, "hospitalLevelName");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNameNotLike(String value) {
            addCriterion("hospital_level_name not like", value, "hospitalLevelName");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNameIn(List<String> values) {
            addCriterion("hospital_level_name in", values, "hospitalLevelName");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNameNotIn(List<String> values) {
            addCriterion("hospital_level_name not in", values, "hospitalLevelName");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNameBetween(String value1, String value2) {
            addCriterion("hospital_level_name between", value1, value2, "hospitalLevelName");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNameNotBetween(String value1, String value2) {
            addCriterion("hospital_level_name not between", value1, value2, "hospitalLevelName");
            return (Criteria) this;
        }

        public Criteria andHospitalPhoneIsNull() {
            addCriterion("hospital_phone is null");
            return (Criteria) this;
        }

        public Criteria andHospitalPhoneIsNotNull() {
            addCriterion("hospital_phone is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalPhoneEqualTo(String value) {
            addCriterion("hospital_phone =", value, "hospitalPhone");
            return (Criteria) this;
        }

        public Criteria andHospitalPhoneNotEqualTo(String value) {
            addCriterion("hospital_phone <>", value, "hospitalPhone");
            return (Criteria) this;
        }

        public Criteria andHospitalPhoneGreaterThan(String value) {
            addCriterion("hospital_phone >", value, "hospitalPhone");
            return (Criteria) this;
        }

        public Criteria andHospitalPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_phone >=", value, "hospitalPhone");
            return (Criteria) this;
        }

        public Criteria andHospitalPhoneLessThan(String value) {
            addCriterion("hospital_phone <", value, "hospitalPhone");
            return (Criteria) this;
        }

        public Criteria andHospitalPhoneLessThanOrEqualTo(String value) {
            addCriterion("hospital_phone <=", value, "hospitalPhone");
            return (Criteria) this;
        }

        public Criteria andHospitalPhoneLike(String value) {
            addCriterion("hospital_phone like", value, "hospitalPhone");
            return (Criteria) this;
        }

        public Criteria andHospitalPhoneNotLike(String value) {
            addCriterion("hospital_phone not like", value, "hospitalPhone");
            return (Criteria) this;
        }

        public Criteria andHospitalPhoneIn(List<String> values) {
            addCriterion("hospital_phone in", values, "hospitalPhone");
            return (Criteria) this;
        }

        public Criteria andHospitalPhoneNotIn(List<String> values) {
            addCriterion("hospital_phone not in", values, "hospitalPhone");
            return (Criteria) this;
        }

        public Criteria andHospitalPhoneBetween(String value1, String value2) {
            addCriterion("hospital_phone between", value1, value2, "hospitalPhone");
            return (Criteria) this;
        }

        public Criteria andHospitalPhoneNotBetween(String value1, String value2) {
            addCriterion("hospital_phone not between", value1, value2, "hospitalPhone");
            return (Criteria) this;
        }

        public Criteria andHospitalOrderCountIsNull() {
            addCriterion("hospital_order_count is null");
            return (Criteria) this;
        }

        public Criteria andHospitalOrderCountIsNotNull() {
            addCriterion("hospital_order_count is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalOrderCountEqualTo(Long value) {
            addCriterion("hospital_order_count =", value, "hospitalOrderCount");
            return (Criteria) this;
        }

        public Criteria andHospitalOrderCountNotEqualTo(Long value) {
            addCriterion("hospital_order_count <>", value, "hospitalOrderCount");
            return (Criteria) this;
        }

        public Criteria andHospitalOrderCountGreaterThan(Long value) {
            addCriterion("hospital_order_count >", value, "hospitalOrderCount");
            return (Criteria) this;
        }

        public Criteria andHospitalOrderCountGreaterThanOrEqualTo(Long value) {
            addCriterion("hospital_order_count >=", value, "hospitalOrderCount");
            return (Criteria) this;
        }

        public Criteria andHospitalOrderCountLessThan(Long value) {
            addCriterion("hospital_order_count <", value, "hospitalOrderCount");
            return (Criteria) this;
        }

        public Criteria andHospitalOrderCountLessThanOrEqualTo(Long value) {
            addCriterion("hospital_order_count <=", value, "hospitalOrderCount");
            return (Criteria) this;
        }

        public Criteria andHospitalOrderCountIn(List<Long> values) {
            addCriterion("hospital_order_count in", values, "hospitalOrderCount");
            return (Criteria) this;
        }

        public Criteria andHospitalOrderCountNotIn(List<Long> values) {
            addCriterion("hospital_order_count not in", values, "hospitalOrderCount");
            return (Criteria) this;
        }

        public Criteria andHospitalOrderCountBetween(Long value1, Long value2) {
            addCriterion("hospital_order_count between", value1, value2, "hospitalOrderCount");
            return (Criteria) this;
        }

        public Criteria andHospitalOrderCountNotBetween(Long value1, Long value2) {
            addCriterion("hospital_order_count not between", value1, value2, "hospitalOrderCount");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andBakCode1IsNull() {
            addCriterion("bak_code1 is null");
            return (Criteria) this;
        }

        public Criteria andBakCode1IsNotNull() {
            addCriterion("bak_code1 is not null");
            return (Criteria) this;
        }

        public Criteria andBakCode1EqualTo(String value) {
            addCriterion("bak_code1 =", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1NotEqualTo(String value) {
            addCriterion("bak_code1 <>", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1GreaterThan(String value) {
            addCriterion("bak_code1 >", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1GreaterThanOrEqualTo(String value) {
            addCriterion("bak_code1 >=", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1LessThan(String value) {
            addCriterion("bak_code1 <", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1LessThanOrEqualTo(String value) {
            addCriterion("bak_code1 <=", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1Like(String value) {
            addCriterion("bak_code1 like", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1NotLike(String value) {
            addCriterion("bak_code1 not like", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1In(List<String> values) {
            addCriterion("bak_code1 in", values, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1NotIn(List<String> values) {
            addCriterion("bak_code1 not in", values, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1Between(String value1, String value2) {
            addCriterion("bak_code1 between", value1, value2, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1NotBetween(String value1, String value2) {
            addCriterion("bak_code1 not between", value1, value2, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode2IsNull() {
            addCriterion("bak_code2 is null");
            return (Criteria) this;
        }

        public Criteria andBakCode2IsNotNull() {
            addCriterion("bak_code2 is not null");
            return (Criteria) this;
        }

        public Criteria andBakCode2EqualTo(String value) {
            addCriterion("bak_code2 =", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2NotEqualTo(String value) {
            addCriterion("bak_code2 <>", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2GreaterThan(String value) {
            addCriterion("bak_code2 >", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2GreaterThanOrEqualTo(String value) {
            addCriterion("bak_code2 >=", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2LessThan(String value) {
            addCriterion("bak_code2 <", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2LessThanOrEqualTo(String value) {
            addCriterion("bak_code2 <=", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2Like(String value) {
            addCriterion("bak_code2 like", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2NotLike(String value) {
            addCriterion("bak_code2 not like", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2In(List<String> values) {
            addCriterion("bak_code2 in", values, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2NotIn(List<String> values) {
            addCriterion("bak_code2 not in", values, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2Between(String value1, String value2) {
            addCriterion("bak_code2 between", value1, value2, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2NotBetween(String value1, String value2) {
            addCriterion("bak_code2 not between", value1, value2, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andHaschildIsNull() {
            addCriterion("haschild is null");
            return (Criteria) this;
        }

        public Criteria andHaschildIsNotNull() {
            addCriterion("haschild is not null");
            return (Criteria) this;
        }

        public Criteria andHaschildEqualTo(String value) {
            addCriterion("haschild =", value, "haschild");
            return (Criteria) this;
        }

        public Criteria andHaschildNotEqualTo(String value) {
            addCriterion("haschild <>", value, "haschild");
            return (Criteria) this;
        }

        public Criteria andHaschildGreaterThan(String value) {
            addCriterion("haschild >", value, "haschild");
            return (Criteria) this;
        }

        public Criteria andHaschildGreaterThanOrEqualTo(String value) {
            addCriterion("haschild >=", value, "haschild");
            return (Criteria) this;
        }

        public Criteria andHaschildLessThan(String value) {
            addCriterion("haschild <", value, "haschild");
            return (Criteria) this;
        }

        public Criteria andHaschildLessThanOrEqualTo(String value) {
            addCriterion("haschild <=", value, "haschild");
            return (Criteria) this;
        }

        public Criteria andHaschildLike(String value) {
            addCriterion("haschild like", value, "haschild");
            return (Criteria) this;
        }

        public Criteria andHaschildNotLike(String value) {
            addCriterion("haschild not like", value, "haschild");
            return (Criteria) this;
        }

        public Criteria andHaschildIn(List<String> values) {
            addCriterion("haschild in", values, "haschild");
            return (Criteria) this;
        }

        public Criteria andHaschildNotIn(List<String> values) {
            addCriterion("haschild not in", values, "haschild");
            return (Criteria) this;
        }

        public Criteria andHaschildBetween(String value1, String value2) {
            addCriterion("haschild between", value1, value2, "haschild");
            return (Criteria) this;
        }

        public Criteria andHaschildNotBetween(String value1, String value2) {
            addCriterion("haschild not between", value1, value2, "haschild");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(String value) {
            addCriterion("parent_id =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(String value) {
            addCriterion("parent_id <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(String value) {
            addCriterion("parent_id >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(String value) {
            addCriterion("parent_id >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(String value) {
            addCriterion("parent_id <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(String value) {
            addCriterion("parent_id <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLike(String value) {
            addCriterion("parent_id like", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotLike(String value) {
            addCriterion("parent_id not like", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<String> values) {
            addCriterion("parent_id in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<String> values) {
            addCriterion("parent_id not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(String value1, String value2) {
            addCriterion("parent_id between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(String value1, String value2) {
            addCriterion("parent_id not between", value1, value2, "parentId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_hospital
     *
     * @mbggenerated do_not_delete_during_merge Sat Feb 13 18:45:57 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_hospital
     *
     * @mbggenerated Sat Feb 13 18:45:57 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}