package com.liurq.server.model;

import java.util.Date;

public class Illness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_illness.illness_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String illnessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_illness.illness_name
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String illnessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_illness.illness_alias
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String illnessAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_illness.deleted
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_illness.department_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_illness.create_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_illness.update_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_illness.illness_id
     *
     * @return the value of td_illness.illness_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getIllnessId() {
        return illnessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_illness.illness_id
     *
     * @param illnessId the value for td_illness.illness_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setIllnessId(String illnessId) {
        this.illnessId = illnessId == null ? null : illnessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_illness.illness_name
     *
     * @return the value of td_illness.illness_name
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getIllnessName() {
        return illnessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_illness.illness_name
     *
     * @param illnessName the value for td_illness.illness_name
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setIllnessName(String illnessName) {
        this.illnessName = illnessName == null ? null : illnessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_illness.illness_alias
     *
     * @return the value of td_illness.illness_alias
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getIllnessAlias() {
        return illnessAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_illness.illness_alias
     *
     * @param illnessAlias the value for td_illness.illness_alias
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setIllnessAlias(String illnessAlias) {
        this.illnessAlias = illnessAlias == null ? null : illnessAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_illness.deleted
     *
     * @return the value of td_illness.deleted
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_illness.deleted
     *
     * @param deleted the value for td_illness.deleted
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_illness.department_id
     *
     * @return the value of td_illness.department_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_illness.department_id
     *
     * @param departmentId the value for td_illness.department_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_illness.create_date
     *
     * @return the value of td_illness.create_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_illness.create_date
     *
     * @param createDate the value for td_illness.create_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_illness.update_date
     *
     * @return the value of td_illness.update_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_illness.update_date
     *
     * @param updateDate the value for td_illness.update_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}