package com.liurq.server.model;

import java.util.Date;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.member_id
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.member_name
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    private String memberName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.password
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.member_parent
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    private String memberParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.type
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.status
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.info_id
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    private String infoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.create_date
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.update_date
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.create_user
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    private String createUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.member_id
     *
     * @return the value of tb_member.member_id
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.member_id
     *
     * @param memberId the value for tb_member.member_id
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.member_name
     *
     * @return the value of tb_member.member_name
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.member_name
     *
     * @param memberName the value for tb_member.member_name
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.password
     *
     * @return the value of tb_member.password
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.password
     *
     * @param password the value for tb_member.password
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.member_parent
     *
     * @return the value of tb_member.member_parent
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    public String getMemberParent() {
        return memberParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.member_parent
     *
     * @param memberParent the value for tb_member.member_parent
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    public void setMemberParent(String memberParent) {
        this.memberParent = memberParent == null ? null : memberParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.type
     *
     * @return the value of tb_member.type
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.type
     *
     * @param type the value for tb_member.type
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.status
     *
     * @return the value of tb_member.status
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.status
     *
     * @param status the value for tb_member.status
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.info_id
     *
     * @return the value of tb_member.info_id
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    public String getInfoId() {
        return infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.info_id
     *
     * @param infoId the value for tb_member.info_id
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    public void setInfoId(String infoId) {
        this.infoId = infoId == null ? null : infoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.create_date
     *
     * @return the value of tb_member.create_date
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.create_date
     *
     * @param createDate the value for tb_member.create_date
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.update_date
     *
     * @return the value of tb_member.update_date
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.update_date
     *
     * @param updateDate the value for tb_member.update_date
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.create_user
     *
     * @return the value of tb_member.create_user
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.create_user
     *
     * @param createUser the value for tb_member.create_user
     *
     * @mbggenerated Mon Mar 29 15:02:24 CST 2021
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }
}