package com.liurq.server.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PatientExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public PatientExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPatientIdIsNull() {
            addCriterion("patient_id is null");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNotNull() {
            addCriterion("patient_id is not null");
            return (Criteria) this;
        }

        public Criteria andPatientIdEqualTo(String value) {
            addCriterion("patient_id =", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotEqualTo(String value) {
            addCriterion("patient_id <>", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThan(String value) {
            addCriterion("patient_id >", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThanOrEqualTo(String value) {
            addCriterion("patient_id >=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThan(String value) {
            addCriterion("patient_id <", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThanOrEqualTo(String value) {
            addCriterion("patient_id <=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLike(String value) {
            addCriterion("patient_id like", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotLike(String value) {
            addCriterion("patient_id not like", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdIn(List<String> values) {
            addCriterion("patient_id in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotIn(List<String> values) {
            addCriterion("patient_id not in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdBetween(String value1, String value2) {
            addCriterion("patient_id between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotBetween(String value1, String value2) {
            addCriterion("patient_id not between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdCardIsNull() {
            addCriterion("patient_id_card is null");
            return (Criteria) this;
        }

        public Criteria andPatientIdCardIsNotNull() {
            addCriterion("patient_id_card is not null");
            return (Criteria) this;
        }

        public Criteria andPatientIdCardEqualTo(String value) {
            addCriterion("patient_id_card =", value, "patientIdCard");
            return (Criteria) this;
        }

        public Criteria andPatientIdCardNotEqualTo(String value) {
            addCriterion("patient_id_card <>", value, "patientIdCard");
            return (Criteria) this;
        }

        public Criteria andPatientIdCardGreaterThan(String value) {
            addCriterion("patient_id_card >", value, "patientIdCard");
            return (Criteria) this;
        }

        public Criteria andPatientIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("patient_id_card >=", value, "patientIdCard");
            return (Criteria) this;
        }

        public Criteria andPatientIdCardLessThan(String value) {
            addCriterion("patient_id_card <", value, "patientIdCard");
            return (Criteria) this;
        }

        public Criteria andPatientIdCardLessThanOrEqualTo(String value) {
            addCriterion("patient_id_card <=", value, "patientIdCard");
            return (Criteria) this;
        }

        public Criteria andPatientIdCardLike(String value) {
            addCriterion("patient_id_card like", value, "patientIdCard");
            return (Criteria) this;
        }

        public Criteria andPatientIdCardNotLike(String value) {
            addCriterion("patient_id_card not like", value, "patientIdCard");
            return (Criteria) this;
        }

        public Criteria andPatientIdCardIn(List<String> values) {
            addCriterion("patient_id_card in", values, "patientIdCard");
            return (Criteria) this;
        }

        public Criteria andPatientIdCardNotIn(List<String> values) {
            addCriterion("patient_id_card not in", values, "patientIdCard");
            return (Criteria) this;
        }

        public Criteria andPatientIdCardBetween(String value1, String value2) {
            addCriterion("patient_id_card between", value1, value2, "patientIdCard");
            return (Criteria) this;
        }

        public Criteria andPatientIdCardNotBetween(String value1, String value2) {
            addCriterion("patient_id_card not between", value1, value2, "patientIdCard");
            return (Criteria) this;
        }

        public Criteria andPatientNameIsNull() {
            addCriterion("patient_name is null");
            return (Criteria) this;
        }

        public Criteria andPatientNameIsNotNull() {
            addCriterion("patient_name is not null");
            return (Criteria) this;
        }

        public Criteria andPatientNameEqualTo(String value) {
            addCriterion("patient_name =", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameNotEqualTo(String value) {
            addCriterion("patient_name <>", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameGreaterThan(String value) {
            addCriterion("patient_name >", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameGreaterThanOrEqualTo(String value) {
            addCriterion("patient_name >=", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameLessThan(String value) {
            addCriterion("patient_name <", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameLessThanOrEqualTo(String value) {
            addCriterion("patient_name <=", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameLike(String value) {
            addCriterion("patient_name like", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameNotLike(String value) {
            addCriterion("patient_name not like", value, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameIn(List<String> values) {
            addCriterion("patient_name in", values, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameNotIn(List<String> values) {
            addCriterion("patient_name not in", values, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameBetween(String value1, String value2) {
            addCriterion("patient_name between", value1, value2, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientNameNotBetween(String value1, String value2) {
            addCriterion("patient_name not between", value1, value2, "patientName");
            return (Criteria) this;
        }

        public Criteria andPatientSexIsNull() {
            addCriterion("patient_sex is null");
            return (Criteria) this;
        }

        public Criteria andPatientSexIsNotNull() {
            addCriterion("patient_sex is not null");
            return (Criteria) this;
        }

        public Criteria andPatientSexEqualTo(String value) {
            addCriterion("patient_sex =", value, "patientSex");
            return (Criteria) this;
        }

        public Criteria andPatientSexNotEqualTo(String value) {
            addCriterion("patient_sex <>", value, "patientSex");
            return (Criteria) this;
        }

        public Criteria andPatientSexGreaterThan(String value) {
            addCriterion("patient_sex >", value, "patientSex");
            return (Criteria) this;
        }

        public Criteria andPatientSexGreaterThanOrEqualTo(String value) {
            addCriterion("patient_sex >=", value, "patientSex");
            return (Criteria) this;
        }

        public Criteria andPatientSexLessThan(String value) {
            addCriterion("patient_sex <", value, "patientSex");
            return (Criteria) this;
        }

        public Criteria andPatientSexLessThanOrEqualTo(String value) {
            addCriterion("patient_sex <=", value, "patientSex");
            return (Criteria) this;
        }

        public Criteria andPatientSexLike(String value) {
            addCriterion("patient_sex like", value, "patientSex");
            return (Criteria) this;
        }

        public Criteria andPatientSexNotLike(String value) {
            addCriterion("patient_sex not like", value, "patientSex");
            return (Criteria) this;
        }

        public Criteria andPatientSexIn(List<String> values) {
            addCriterion("patient_sex in", values, "patientSex");
            return (Criteria) this;
        }

        public Criteria andPatientSexNotIn(List<String> values) {
            addCriterion("patient_sex not in", values, "patientSex");
            return (Criteria) this;
        }

        public Criteria andPatientSexBetween(String value1, String value2) {
            addCriterion("patient_sex between", value1, value2, "patientSex");
            return (Criteria) this;
        }

        public Criteria andPatientSexNotBetween(String value1, String value2) {
            addCriterion("patient_sex not between", value1, value2, "patientSex");
            return (Criteria) this;
        }

        public Criteria andPatientParentIdIsNull() {
            addCriterion("patient_parent_id is null");
            return (Criteria) this;
        }

        public Criteria andPatientParentIdIsNotNull() {
            addCriterion("patient_parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andPatientParentIdEqualTo(String value) {
            addCriterion("patient_parent_id =", value, "patientParentId");
            return (Criteria) this;
        }

        public Criteria andPatientParentIdNotEqualTo(String value) {
            addCriterion("patient_parent_id <>", value, "patientParentId");
            return (Criteria) this;
        }

        public Criteria andPatientParentIdGreaterThan(String value) {
            addCriterion("patient_parent_id >", value, "patientParentId");
            return (Criteria) this;
        }

        public Criteria andPatientParentIdGreaterThanOrEqualTo(String value) {
            addCriterion("patient_parent_id >=", value, "patientParentId");
            return (Criteria) this;
        }

        public Criteria andPatientParentIdLessThan(String value) {
            addCriterion("patient_parent_id <", value, "patientParentId");
            return (Criteria) this;
        }

        public Criteria andPatientParentIdLessThanOrEqualTo(String value) {
            addCriterion("patient_parent_id <=", value, "patientParentId");
            return (Criteria) this;
        }

        public Criteria andPatientParentIdLike(String value) {
            addCriterion("patient_parent_id like", value, "patientParentId");
            return (Criteria) this;
        }

        public Criteria andPatientParentIdNotLike(String value) {
            addCriterion("patient_parent_id not like", value, "patientParentId");
            return (Criteria) this;
        }

        public Criteria andPatientParentIdIn(List<String> values) {
            addCriterion("patient_parent_id in", values, "patientParentId");
            return (Criteria) this;
        }

        public Criteria andPatientParentIdNotIn(List<String> values) {
            addCriterion("patient_parent_id not in", values, "patientParentId");
            return (Criteria) this;
        }

        public Criteria andPatientParentIdBetween(String value1, String value2) {
            addCriterion("patient_parent_id between", value1, value2, "patientParentId");
            return (Criteria) this;
        }

        public Criteria andPatientParentIdNotBetween(String value1, String value2) {
            addCriterion("patient_parent_id not between", value1, value2, "patientParentId");
            return (Criteria) this;
        }

        public Criteria andPatientPhoneIsNull() {
            addCriterion("patient_phone is null");
            return (Criteria) this;
        }

        public Criteria andPatientPhoneIsNotNull() {
            addCriterion("patient_phone is not null");
            return (Criteria) this;
        }

        public Criteria andPatientPhoneEqualTo(String value) {
            addCriterion("patient_phone =", value, "patientPhone");
            return (Criteria) this;
        }

        public Criteria andPatientPhoneNotEqualTo(String value) {
            addCriterion("patient_phone <>", value, "patientPhone");
            return (Criteria) this;
        }

        public Criteria andPatientPhoneGreaterThan(String value) {
            addCriterion("patient_phone >", value, "patientPhone");
            return (Criteria) this;
        }

        public Criteria andPatientPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("patient_phone >=", value, "patientPhone");
            return (Criteria) this;
        }

        public Criteria andPatientPhoneLessThan(String value) {
            addCriterion("patient_phone <", value, "patientPhone");
            return (Criteria) this;
        }

        public Criteria andPatientPhoneLessThanOrEqualTo(String value) {
            addCriterion("patient_phone <=", value, "patientPhone");
            return (Criteria) this;
        }

        public Criteria andPatientPhoneLike(String value) {
            addCriterion("patient_phone like", value, "patientPhone");
            return (Criteria) this;
        }

        public Criteria andPatientPhoneNotLike(String value) {
            addCriterion("patient_phone not like", value, "patientPhone");
            return (Criteria) this;
        }

        public Criteria andPatientPhoneIn(List<String> values) {
            addCriterion("patient_phone in", values, "patientPhone");
            return (Criteria) this;
        }

        public Criteria andPatientPhoneNotIn(List<String> values) {
            addCriterion("patient_phone not in", values, "patientPhone");
            return (Criteria) this;
        }

        public Criteria andPatientPhoneBetween(String value1, String value2) {
            addCriterion("patient_phone between", value1, value2, "patientPhone");
            return (Criteria) this;
        }

        public Criteria andPatientPhoneNotBetween(String value1, String value2) {
            addCriterion("patient_phone not between", value1, value2, "patientPhone");
            return (Criteria) this;
        }

        public Criteria andPatientAddressIsNull() {
            addCriterion("patient_address is null");
            return (Criteria) this;
        }

        public Criteria andPatientAddressIsNotNull() {
            addCriterion("patient_address is not null");
            return (Criteria) this;
        }

        public Criteria andPatientAddressEqualTo(String value) {
            addCriterion("patient_address =", value, "patientAddress");
            return (Criteria) this;
        }

        public Criteria andPatientAddressNotEqualTo(String value) {
            addCriterion("patient_address <>", value, "patientAddress");
            return (Criteria) this;
        }

        public Criteria andPatientAddressGreaterThan(String value) {
            addCriterion("patient_address >", value, "patientAddress");
            return (Criteria) this;
        }

        public Criteria andPatientAddressGreaterThanOrEqualTo(String value) {
            addCriterion("patient_address >=", value, "patientAddress");
            return (Criteria) this;
        }

        public Criteria andPatientAddressLessThan(String value) {
            addCriterion("patient_address <", value, "patientAddress");
            return (Criteria) this;
        }

        public Criteria andPatientAddressLessThanOrEqualTo(String value) {
            addCriterion("patient_address <=", value, "patientAddress");
            return (Criteria) this;
        }

        public Criteria andPatientAddressLike(String value) {
            addCriterion("patient_address like", value, "patientAddress");
            return (Criteria) this;
        }

        public Criteria andPatientAddressNotLike(String value) {
            addCriterion("patient_address not like", value, "patientAddress");
            return (Criteria) this;
        }

        public Criteria andPatientAddressIn(List<String> values) {
            addCriterion("patient_address in", values, "patientAddress");
            return (Criteria) this;
        }

        public Criteria andPatientAddressNotIn(List<String> values) {
            addCriterion("patient_address not in", values, "patientAddress");
            return (Criteria) this;
        }

        public Criteria andPatientAddressBetween(String value1, String value2) {
            addCriterion("patient_address between", value1, value2, "patientAddress");
            return (Criteria) this;
        }

        public Criteria andPatientAddressNotBetween(String value1, String value2) {
            addCriterion("patient_address not between", value1, value2, "patientAddress");
            return (Criteria) this;
        }

        public Criteria andPatientRelationIsNull() {
            addCriterion("patient_relation is null");
            return (Criteria) this;
        }

        public Criteria andPatientRelationIsNotNull() {
            addCriterion("patient_relation is not null");
            return (Criteria) this;
        }

        public Criteria andPatientRelationEqualTo(String value) {
            addCriterion("patient_relation =", value, "patientRelation");
            return (Criteria) this;
        }

        public Criteria andPatientRelationNotEqualTo(String value) {
            addCriterion("patient_relation <>", value, "patientRelation");
            return (Criteria) this;
        }

        public Criteria andPatientRelationGreaterThan(String value) {
            addCriterion("patient_relation >", value, "patientRelation");
            return (Criteria) this;
        }

        public Criteria andPatientRelationGreaterThanOrEqualTo(String value) {
            addCriterion("patient_relation >=", value, "patientRelation");
            return (Criteria) this;
        }

        public Criteria andPatientRelationLessThan(String value) {
            addCriterion("patient_relation <", value, "patientRelation");
            return (Criteria) this;
        }

        public Criteria andPatientRelationLessThanOrEqualTo(String value) {
            addCriterion("patient_relation <=", value, "patientRelation");
            return (Criteria) this;
        }

        public Criteria andPatientRelationLike(String value) {
            addCriterion("patient_relation like", value, "patientRelation");
            return (Criteria) this;
        }

        public Criteria andPatientRelationNotLike(String value) {
            addCriterion("patient_relation not like", value, "patientRelation");
            return (Criteria) this;
        }

        public Criteria andPatientRelationIn(List<String> values) {
            addCriterion("patient_relation in", values, "patientRelation");
            return (Criteria) this;
        }

        public Criteria andPatientRelationNotIn(List<String> values) {
            addCriterion("patient_relation not in", values, "patientRelation");
            return (Criteria) this;
        }

        public Criteria andPatientRelationBetween(String value1, String value2) {
            addCriterion("patient_relation between", value1, value2, "patientRelation");
            return (Criteria) this;
        }

        public Criteria andPatientRelationNotBetween(String value1, String value2) {
            addCriterion("patient_relation not between", value1, value2, "patientRelation");
            return (Criteria) this;
        }

        public Criteria andPatientImageIsNull() {
            addCriterion("patient_image is null");
            return (Criteria) this;
        }

        public Criteria andPatientImageIsNotNull() {
            addCriterion("patient_image is not null");
            return (Criteria) this;
        }

        public Criteria andPatientImageEqualTo(String value) {
            addCriterion("patient_image =", value, "patientImage");
            return (Criteria) this;
        }

        public Criteria andPatientImageNotEqualTo(String value) {
            addCriterion("patient_image <>", value, "patientImage");
            return (Criteria) this;
        }

        public Criteria andPatientImageGreaterThan(String value) {
            addCriterion("patient_image >", value, "patientImage");
            return (Criteria) this;
        }

        public Criteria andPatientImageGreaterThanOrEqualTo(String value) {
            addCriterion("patient_image >=", value, "patientImage");
            return (Criteria) this;
        }

        public Criteria andPatientImageLessThan(String value) {
            addCriterion("patient_image <", value, "patientImage");
            return (Criteria) this;
        }

        public Criteria andPatientImageLessThanOrEqualTo(String value) {
            addCriterion("patient_image <=", value, "patientImage");
            return (Criteria) this;
        }

        public Criteria andPatientImageLike(String value) {
            addCriterion("patient_image like", value, "patientImage");
            return (Criteria) this;
        }

        public Criteria andPatientImageNotLike(String value) {
            addCriterion("patient_image not like", value, "patientImage");
            return (Criteria) this;
        }

        public Criteria andPatientImageIn(List<String> values) {
            addCriterion("patient_image in", values, "patientImage");
            return (Criteria) this;
        }

        public Criteria andPatientImageNotIn(List<String> values) {
            addCriterion("patient_image not in", values, "patientImage");
            return (Criteria) this;
        }

        public Criteria andPatientImageBetween(String value1, String value2) {
            addCriterion("patient_image between", value1, value2, "patientImage");
            return (Criteria) this;
        }

        public Criteria andPatientImageNotBetween(String value1, String value2) {
            addCriterion("patient_image not between", value1, value2, "patientImage");
            return (Criteria) this;
        }

        public Criteria andPatientBirthdayIsNull() {
            addCriterion("patient_birthday is null");
            return (Criteria) this;
        }

        public Criteria andPatientBirthdayIsNotNull() {
            addCriterion("patient_birthday is not null");
            return (Criteria) this;
        }

        public Criteria andPatientBirthdayEqualTo(Date value) {
            addCriterion("patient_birthday =", value, "patientBirthday");
            return (Criteria) this;
        }

        public Criteria andPatientBirthdayNotEqualTo(Date value) {
            addCriterion("patient_birthday <>", value, "patientBirthday");
            return (Criteria) this;
        }

        public Criteria andPatientBirthdayGreaterThan(Date value) {
            addCriterion("patient_birthday >", value, "patientBirthday");
            return (Criteria) this;
        }

        public Criteria andPatientBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterion("patient_birthday >=", value, "patientBirthday");
            return (Criteria) this;
        }

        public Criteria andPatientBirthdayLessThan(Date value) {
            addCriterion("patient_birthday <", value, "patientBirthday");
            return (Criteria) this;
        }

        public Criteria andPatientBirthdayLessThanOrEqualTo(Date value) {
            addCriterion("patient_birthday <=", value, "patientBirthday");
            return (Criteria) this;
        }

        public Criteria andPatientBirthdayIn(List<Date> values) {
            addCriterion("patient_birthday in", values, "patientBirthday");
            return (Criteria) this;
        }

        public Criteria andPatientBirthdayNotIn(List<Date> values) {
            addCriterion("patient_birthday not in", values, "patientBirthday");
            return (Criteria) this;
        }

        public Criteria andPatientBirthdayBetween(Date value1, Date value2) {
            addCriterion("patient_birthday between", value1, value2, "patientBirthday");
            return (Criteria) this;
        }

        public Criteria andPatientBirthdayNotBetween(Date value1, Date value2) {
            addCriterion("patient_birthday not between", value1, value2, "patientBirthday");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andBakCode1IsNull() {
            addCriterion("bak_code1 is null");
            return (Criteria) this;
        }

        public Criteria andBakCode1IsNotNull() {
            addCriterion("bak_code1 is not null");
            return (Criteria) this;
        }

        public Criteria andBakCode1EqualTo(String value) {
            addCriterion("bak_code1 =", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1NotEqualTo(String value) {
            addCriterion("bak_code1 <>", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1GreaterThan(String value) {
            addCriterion("bak_code1 >", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1GreaterThanOrEqualTo(String value) {
            addCriterion("bak_code1 >=", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1LessThan(String value) {
            addCriterion("bak_code1 <", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1LessThanOrEqualTo(String value) {
            addCriterion("bak_code1 <=", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1Like(String value) {
            addCriterion("bak_code1 like", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1NotLike(String value) {
            addCriterion("bak_code1 not like", value, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1In(List<String> values) {
            addCriterion("bak_code1 in", values, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1NotIn(List<String> values) {
            addCriterion("bak_code1 not in", values, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1Between(String value1, String value2) {
            addCriterion("bak_code1 between", value1, value2, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode1NotBetween(String value1, String value2) {
            addCriterion("bak_code1 not between", value1, value2, "bakCode1");
            return (Criteria) this;
        }

        public Criteria andBakCode2IsNull() {
            addCriterion("bak_code2 is null");
            return (Criteria) this;
        }

        public Criteria andBakCode2IsNotNull() {
            addCriterion("bak_code2 is not null");
            return (Criteria) this;
        }

        public Criteria andBakCode2EqualTo(String value) {
            addCriterion("bak_code2 =", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2NotEqualTo(String value) {
            addCriterion("bak_code2 <>", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2GreaterThan(String value) {
            addCriterion("bak_code2 >", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2GreaterThanOrEqualTo(String value) {
            addCriterion("bak_code2 >=", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2LessThan(String value) {
            addCriterion("bak_code2 <", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2LessThanOrEqualTo(String value) {
            addCriterion("bak_code2 <=", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2Like(String value) {
            addCriterion("bak_code2 like", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2NotLike(String value) {
            addCriterion("bak_code2 not like", value, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2In(List<String> values) {
            addCriterion("bak_code2 in", values, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2NotIn(List<String> values) {
            addCriterion("bak_code2 not in", values, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2Between(String value1, String value2) {
            addCriterion("bak_code2 between", value1, value2, "bakCode2");
            return (Criteria) this;
        }

        public Criteria andBakCode2NotBetween(String value1, String value2) {
            addCriterion("bak_code2 not between", value1, value2, "bakCode2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_user_patient
     *
     * @mbggenerated do_not_delete_during_merge Wed Feb 03 19:23:50 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}