package com.liurq.server.model;

import java.util.Date;

public class TagRelevance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_tag_relevance.id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_tag_relevance.tag_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_tag_relevance.tag_rel_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String tagRelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_tag_relevance.create_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_tag_relevance.update_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_tag_relevance.deleted
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_tag_relevance.id
     *
     * @return the value of tr_tag_relevance.id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_tag_relevance.id
     *
     * @param id the value for tr_tag_relevance.id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_tag_relevance.tag_id
     *
     * @return the value of tr_tag_relevance.tag_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_tag_relevance.tag_id
     *
     * @param tagId the value for tr_tag_relevance.tag_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setTagId(String tagId) {
        this.tagId = tagId == null ? null : tagId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_tag_relevance.tag_rel_id
     *
     * @return the value of tr_tag_relevance.tag_rel_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getTagRelId() {
        return tagRelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_tag_relevance.tag_rel_id
     *
     * @param tagRelId the value for tr_tag_relevance.tag_rel_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setTagRelId(String tagRelId) {
        this.tagRelId = tagRelId == null ? null : tagRelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_tag_relevance.create_date
     *
     * @return the value of tr_tag_relevance.create_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_tag_relevance.create_date
     *
     * @param createDate the value for tr_tag_relevance.create_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_tag_relevance.update_date
     *
     * @return the value of tr_tag_relevance.update_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_tag_relevance.update_date
     *
     * @param updateDate the value for tr_tag_relevance.update_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_tag_relevance.deleted
     *
     * @return the value of tr_tag_relevance.deleted
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_tag_relevance.deleted
     *
     * @param deleted the value for tr_tag_relevance.deleted
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }
}