package com.liurq.server.model;

public class TownShip {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_town_ship.id
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_town_ship.code_prov
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    private String codeProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_town_ship.name_prov
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    private String nameProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_town_ship.code_city
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    private String codeCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_town_ship.name_city
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    private String nameCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_town_ship.code_coun
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    private String codeCoun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_town_ship.name_coun
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    private String nameCoun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_town_ship.code_town
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    private String codeTown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_town_ship.name_town
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    private String nameTown;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_town_ship.id
     *
     * @return the value of tb_town_ship.id
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_town_ship.id
     *
     * @param id the value for tb_town_ship.id
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_town_ship.code_prov
     *
     * @return the value of tb_town_ship.code_prov
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    public String getCodeProv() {
        return codeProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_town_ship.code_prov
     *
     * @param codeProv the value for tb_town_ship.code_prov
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    public void setCodeProv(String codeProv) {
        this.codeProv = codeProv == null ? null : codeProv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_town_ship.name_prov
     *
     * @return the value of tb_town_ship.name_prov
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    public String getNameProv() {
        return nameProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_town_ship.name_prov
     *
     * @param nameProv the value for tb_town_ship.name_prov
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    public void setNameProv(String nameProv) {
        this.nameProv = nameProv == null ? null : nameProv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_town_ship.code_city
     *
     * @return the value of tb_town_ship.code_city
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    public String getCodeCity() {
        return codeCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_town_ship.code_city
     *
     * @param codeCity the value for tb_town_ship.code_city
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    public void setCodeCity(String codeCity) {
        this.codeCity = codeCity == null ? null : codeCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_town_ship.name_city
     *
     * @return the value of tb_town_ship.name_city
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    public String getNameCity() {
        return nameCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_town_ship.name_city
     *
     * @param nameCity the value for tb_town_ship.name_city
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    public void setNameCity(String nameCity) {
        this.nameCity = nameCity == null ? null : nameCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_town_ship.code_coun
     *
     * @return the value of tb_town_ship.code_coun
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    public String getCodeCoun() {
        return codeCoun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_town_ship.code_coun
     *
     * @param codeCoun the value for tb_town_ship.code_coun
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    public void setCodeCoun(String codeCoun) {
        this.codeCoun = codeCoun == null ? null : codeCoun.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_town_ship.name_coun
     *
     * @return the value of tb_town_ship.name_coun
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    public String getNameCoun() {
        return nameCoun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_town_ship.name_coun
     *
     * @param nameCoun the value for tb_town_ship.name_coun
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    public void setNameCoun(String nameCoun) {
        this.nameCoun = nameCoun == null ? null : nameCoun.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_town_ship.code_town
     *
     * @return the value of tb_town_ship.code_town
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    public String getCodeTown() {
        return codeTown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_town_ship.code_town
     *
     * @param codeTown the value for tb_town_ship.code_town
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    public void setCodeTown(String codeTown) {
        this.codeTown = codeTown == null ? null : codeTown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_town_ship.name_town
     *
     * @return the value of tb_town_ship.name_town
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    public String getNameTown() {
        return nameTown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_town_ship.name_town
     *
     * @param nameTown the value for tb_town_ship.name_town
     *
     * @mbggenerated Mon Mar 29 15:17:23 CST 2021
     */
    public void setNameTown(String nameTown) {
        this.nameTown = nameTown == null ? null : nameTown.trim();
    }
}