package com.liurq.server.model;

import java.util.Date;

public class Type {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_type.type_id
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_type.type_name
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_type.status
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_type.create_date
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_type.update_date
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_type.type_id
     *
     * @return the value of tb_type.type_id
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_type.type_id
     *
     * @param typeId the value for tb_type.type_id
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_type.type_name
     *
     * @return the value of tb_type.type_name
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_type.type_name
     *
     * @param typeName the value for tb_type.type_name
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_type.status
     *
     * @return the value of tb_type.status
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_type.status
     *
     * @param status the value for tb_type.status
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_type.create_date
     *
     * @return the value of tb_type.create_date
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_type.create_date
     *
     * @param createDate the value for tb_type.create_date
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_type.update_date
     *
     * @return the value of tb_type.update_date
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_type.update_date
     *
     * @param updateDate the value for tb_type.update_date
     *
     * @mbggenerated Sat Feb 13 18:29:42 CST 2021
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}