package com.liurq.server.model;

import java.util.Date;

public class UserRegistration {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_registration.id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_registration.user_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_registration.hospital_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String hospitalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_registration.department_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_registration.doctor_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_registration.reg_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private Date regDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_registration.create_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_registration.update_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_registration.num
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_registration.status
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_registration.id
     *
     * @return the value of tb_user_registration.id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_registration.id
     *
     * @param id the value for tb_user_registration.id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_registration.user_id
     *
     * @return the value of tb_user_registration.user_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_registration.user_id
     *
     * @param userId the value for tb_user_registration.user_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_registration.hospital_id
     *
     * @return the value of tb_user_registration.hospital_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_registration.hospital_id
     *
     * @param hospitalId the value for tb_user_registration.hospital_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId == null ? null : hospitalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_registration.department_id
     *
     * @return the value of tb_user_registration.department_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_registration.department_id
     *
     * @param departmentId the value for tb_user_registration.department_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_registration.doctor_id
     *
     * @return the value of tb_user_registration.doctor_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_registration.doctor_id
     *
     * @param doctorId the value for tb_user_registration.doctor_id
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId == null ? null : doctorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_registration.reg_date
     *
     * @return the value of tb_user_registration.reg_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_registration.reg_date
     *
     * @param regDate the value for tb_user_registration.reg_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_registration.create_date
     *
     * @return the value of tb_user_registration.create_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_registration.create_date
     *
     * @param createDate the value for tb_user_registration.create_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_registration.update_date
     *
     * @return the value of tb_user_registration.update_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_registration.update_date
     *
     * @param updateDate the value for tb_user_registration.update_date
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_registration.num
     *
     * @return the value of tb_user_registration.num
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_registration.num
     *
     * @param num the value for tb_user_registration.num
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_registration.status
     *
     * @return the value of tb_user_registration.status
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_registration.status
     *
     * @param status the value for tb_user_registration.status
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}