package com.liurq.server.model;

import java.util.Date;

public class VisitRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_visit_record.id
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_visit_record.visit_id
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    private String visitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_visit_record.num
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_visit_record.status
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_visit_record.create_date
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_visit_record.id
     *
     * @return the value of tb_visit_record.id
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_visit_record.id
     *
     * @param id the value for tb_visit_record.id
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_visit_record.visit_id
     *
     * @return the value of tb_visit_record.visit_id
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    public String getVisitId() {
        return visitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_visit_record.visit_id
     *
     * @param visitId the value for tb_visit_record.visit_id
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    public void setVisitId(String visitId) {
        this.visitId = visitId == null ? null : visitId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_visit_record.num
     *
     * @return the value of tb_visit_record.num
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_visit_record.num
     *
     * @param num the value for tb_visit_record.num
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_visit_record.status
     *
     * @return the value of tb_visit_record.status
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_visit_record.status
     *
     * @param status the value for tb_visit_record.status
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_visit_record.create_date
     *
     * @return the value of tb_visit_record.create_date
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_visit_record.create_date
     *
     * @param createDate the value for tb_visit_record.create_date
     *
     * @mbggenerated Sun Apr 25 22:38:40 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}