server:
  port: 9000
  servlet:
    context-path: /system
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: person-management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1i2ivwv45745tt1uo.mysql.rds.aliyuncs.com:3306/registration?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: buyi
    password: Lps19980318
    type: com.alibaba.druid.pool.DruidDataSource
key:
  redis:
    person:
      authcode: "person::authcode:"
      authToken: "person::token:"


