eureka:
  client:
    service-url:
      #defaultZone: http://47.99.164.233:8761/eureka
      #      defaultZone: http://www.liurq.com:8761/eureka
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: registration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/registration?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    #    username: root
    #    password: root
    url: jdbc:mysql://rm-bp1i2ivwv45745tt1uo.mysql.rds.aliyuncs.com:3306/registration?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: buyi
    password: Lps19980318
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true

key:
  redis:
    person:
      authcode: "person::authcode:"
      authToken: "person::token:"
security:
  openUrl: /**/*.html,/system/js/**,/system/server/login/*,/system/swagger-ui.html,/system/v2/**,/system/swagger-resources/**,/system/webjars/**,


