package com.liurq.server.dao;

import com.liurq.server.model.Hospital;
import com.liurq.server.model.HospitalExample;
import com.liurq.server.model.HospitalWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HospitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int countByExample(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int deleteByExample(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int deleteByPrimaryKey(String hospitalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int insert(HospitalWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int insertSelective(HospitalWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    List<HospitalWithBLOBs> selectByExampleWithBLOBs(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    List<Hospital> selectByExample(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    HospitalWithBLOBs selectByPrimaryKey(String hospitalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByExampleSelective(@Param("record") HospitalWithBLOBs record, @Param("example") HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") HospitalWithBLOBs record, @Param("example") HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByExample(@Param("record") Hospital record, @Param("example") HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByPrimaryKeySelective(HospitalWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(HospitalWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hospital
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByPrimaryKey(Hospital record);
}