package com.liurq.server.dao;

import com.liurq.server.model.Illness;
import com.liurq.server.model.IllnessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IllnessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_illness
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int countByExample(IllnessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_illness
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int deleteByExample(IllnessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_illness
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int deleteByPrimaryKey(String illnessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_illness
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int insert(Illness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_illness
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int insertSelective(Illness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_illness
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    List<Illness> selectByExample(IllnessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_illness
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    Illness selectByPrimaryKey(String illnessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_illness
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByExampleSelective(@Param("record") Illness record, @Param("example") IllnessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_illness
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByExample(@Param("record") Illness record, @Param("example") IllnessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_illness
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByPrimaryKeySelective(Illness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_illness
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByPrimaryKey(Illness record);
}