package com.liurq.server.dao;

import com.liurq.server.model.Patient;
import com.liurq.server.model.PatientExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PatientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int countByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int deleteByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int deleteByPrimaryKey(String patientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int insert(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int insertSelective(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    List<Patient> selectByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    Patient selectByPrimaryKey(String patientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByExampleSelective(@Param("record") Patient record, @Param("example") PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByExample(@Param("record") Patient record, @Param("example") PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByPrimaryKeySelective(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_patient
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByPrimaryKey(Patient record);
}