package com.liurq.server.dao;

import com.liurq.server.model.TagRelevance;
import com.liurq.server.model.TagRelevanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagRelevanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_tag_relevance
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int countByExample(TagRelevanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_tag_relevance
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int deleteByExample(TagRelevanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_tag_relevance
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_tag_relevance
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int insert(TagRelevance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_tag_relevance
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int insertSelective(TagRelevance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_tag_relevance
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    List<TagRelevance> selectByExample(TagRelevanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_tag_relevance
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    TagRelevance selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_tag_relevance
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByExampleSelective(@Param("record") TagRelevance record, @Param("example") TagRelevanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_tag_relevance
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByExample(@Param("record") TagRelevance record, @Param("example") TagRelevanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_tag_relevance
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByPrimaryKeySelective(TagRelevance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_tag_relevance
     *
     * @mbggenerated Wed Feb 03 19:23:50 CST 2021
     */
    int updateByPrimaryKey(TagRelevance record);
}